/** Generated by scripts/generate-icon-loaders.mjs — esbuild entry only, do not import directly. */
import type { Component } from 'vue'
import type { IconographyName } from './iconography.meta'

import AccessibilityIcon from '@lucide/vue/dist/esm/icons/accessibility.mjs'
import ActivityIcon from '@lucide/vue/dist/esm/icons/activity.mjs'
import AirVentIcon from '@lucide/vue/dist/esm/icons/air-vent.mjs'
import AirplayIcon from '@lucide/vue/dist/esm/icons/airplay.mjs'
import AlarmClockIcon from '@lucide/vue/dist/esm/icons/alarm-clock.mjs'
import AlbumIcon from '@lucide/vue/dist/esm/icons/album.mjs'
import AlertCircleIcon from '@lucide/vue/dist/esm/icons/circle-alert.mjs'
import AlertTriangleIcon from '@lucide/vue/dist/esm/icons/triangle-alert.mjs'
import AlignCenterIcon from '@lucide/vue/dist/esm/icons/text-align-center.mjs'
import AlignLeftIcon from '@lucide/vue/dist/esm/icons/text-align-start.mjs'
import AlignRightIcon from '@lucide/vue/dist/esm/icons/text-align-end.mjs'
import AmbulanceIcon from '@lucide/vue/dist/esm/icons/ambulance.mjs'
import AnchorIcon from '@lucide/vue/dist/esm/icons/anchor.mjs'
import AntennaIcon from '@lucide/vue/dist/esm/icons/antenna.mjs'
import ApertureIcon from '@lucide/vue/dist/esm/icons/aperture.mjs'
import AppleIcon from '@lucide/vue/dist/esm/icons/apple.mjs'
import ArchiveIcon from '@lucide/vue/dist/esm/icons/archive.mjs'
import ArchiveRestoreIcon from '@lucide/vue/dist/esm/icons/archive-restore.mjs'
import ArchiveXIcon from '@lucide/vue/dist/esm/icons/archive-x.mjs'
import AreaChartIcon from '@lucide/vue/dist/esm/icons/chart-area.mjs'
import ArmchairIcon from '@lucide/vue/dist/esm/icons/armchair.mjs'
import ArrowDownIcon from '@lucide/vue/dist/esm/icons/arrow-down.mjs'
import ArrowLeftIcon from '@lucide/vue/dist/esm/icons/arrow-left.mjs'
import ArrowRightIcon from '@lucide/vue/dist/esm/icons/arrow-right.mjs'
import ArrowUpIcon from '@lucide/vue/dist/esm/icons/arrow-up.mjs'
import ArrowUpRightIcon from '@lucide/vue/dist/esm/icons/arrow-up-right.mjs'
import AsteriskIcon from '@lucide/vue/dist/esm/icons/asterisk.mjs'
import AtSignIcon from '@lucide/vue/dist/esm/icons/at-sign.mjs'
import AtomIcon from '@lucide/vue/dist/esm/icons/atom.mjs'
import AwardIcon from '@lucide/vue/dist/esm/icons/award.mjs'
import AxeIcon from '@lucide/vue/dist/esm/icons/axe.mjs'
import BabyIcon from '@lucide/vue/dist/esm/icons/baby.mjs'
import BadgeIcon from '@lucide/vue/dist/esm/icons/badge.mjs'
import BadgeAlertIcon from '@lucide/vue/dist/esm/icons/badge-alert.mjs'
import BadgeCentIcon from '@lucide/vue/dist/esm/icons/badge-cent.mjs'
import BadgeCheckIcon from '@lucide/vue/dist/esm/icons/badge-check.mjs'
import BadgeDollarSignIcon from '@lucide/vue/dist/esm/icons/badge-dollar-sign.mjs'
import BadgeEuroIcon from '@lucide/vue/dist/esm/icons/badge-euro.mjs'
import BadgeInfoIcon from '@lucide/vue/dist/esm/icons/badge-info.mjs'
import BadgeMinusIcon from '@lucide/vue/dist/esm/icons/badge-minus.mjs'
import BadgePlusIcon from '@lucide/vue/dist/esm/icons/badge-plus.mjs'
import BadgeXIcon from '@lucide/vue/dist/esm/icons/badge-x.mjs'
import BanIcon from '@lucide/vue/dist/esm/icons/ban.mjs'
import BananaIcon from '@lucide/vue/dist/esm/icons/banana.mjs'
import BanknoteIcon from '@lucide/vue/dist/esm/icons/banknote.mjs'
import BarChart2Icon from '@lucide/vue/dist/esm/icons/chart-no-axes-column.mjs'
import BarChart3Icon from '@lucide/vue/dist/esm/icons/chart-column.mjs'
import BarcodeIcon from '@lucide/vue/dist/esm/icons/barcode.mjs'
import BathIcon from '@lucide/vue/dist/esm/icons/bath.mjs'
import BatteryIcon from '@lucide/vue/dist/esm/icons/battery.mjs'
import BatteryChargingIcon from '@lucide/vue/dist/esm/icons/battery-charging.mjs'
import BatteryFullIcon from '@lucide/vue/dist/esm/icons/battery-full.mjs'
import BatteryLowIcon from '@lucide/vue/dist/esm/icons/battery-low.mjs'
import BeakerIcon from '@lucide/vue/dist/esm/icons/beaker.mjs'
import BedIcon from '@lucide/vue/dist/esm/icons/bed.mjs'
import BedDoubleIcon from '@lucide/vue/dist/esm/icons/bed-double.mjs'
import BedSingleIcon from '@lucide/vue/dist/esm/icons/bed-single.mjs'
import BeefIcon from '@lucide/vue/dist/esm/icons/beef.mjs'
import BellIcon from '@lucide/vue/dist/esm/icons/bell.mjs'
import BellMinusIcon from '@lucide/vue/dist/esm/icons/bell-minus.mjs'
import BellOffIcon from '@lucide/vue/dist/esm/icons/bell-off.mjs'
import BellPlusIcon from '@lucide/vue/dist/esm/icons/bell-plus.mjs'
import BellRingIcon from '@lucide/vue/dist/esm/icons/bell-ring.mjs'
import BikeIcon from '@lucide/vue/dist/esm/icons/bike.mjs'
import BinaryIcon from '@lucide/vue/dist/esm/icons/binary.mjs'
import BirdIcon from '@lucide/vue/dist/esm/icons/bird.mjs'
import BlocksIcon from '@lucide/vue/dist/esm/icons/blocks.mjs'
import BluetoothIcon from '@lucide/vue/dist/esm/icons/bluetooth.mjs'
import BoldIcon from '@lucide/vue/dist/esm/icons/bold.mjs'
import BoltIcon from '@lucide/vue/dist/esm/icons/bolt.mjs'
import BoneIcon from '@lucide/vue/dist/esm/icons/bone.mjs'
import BookIcon from '@lucide/vue/dist/esm/icons/book.mjs'
import BookCheckIcon from '@lucide/vue/dist/esm/icons/book-check.mjs'
import BookCopyIcon from '@lucide/vue/dist/esm/icons/book-copy.mjs'
import BookMarkedIcon from '@lucide/vue/dist/esm/icons/book-marked.mjs'
import BookMinusIcon from '@lucide/vue/dist/esm/icons/book-minus.mjs'
import BookOpenIcon from '@lucide/vue/dist/esm/icons/book-open.mjs'
import BookOpenCheckIcon from '@lucide/vue/dist/esm/icons/book-open-check.mjs'
import BookOpenTextIcon from '@lucide/vue/dist/esm/icons/book-open-text.mjs'
import BookPlusIcon from '@lucide/vue/dist/esm/icons/book-plus.mjs'
import BookTextIcon from '@lucide/vue/dist/esm/icons/book-text.mjs'
import BookUserIcon from '@lucide/vue/dist/esm/icons/book-user.mjs'
import BookXIcon from '@lucide/vue/dist/esm/icons/book-x.mjs'
import BookmarkIcon from '@lucide/vue/dist/esm/icons/bookmark.mjs'
import BookmarkMinusIcon from '@lucide/vue/dist/esm/icons/bookmark-minus.mjs'
import BookmarkPlusIcon from '@lucide/vue/dist/esm/icons/bookmark-plus.mjs'
import BookmarkXIcon from '@lucide/vue/dist/esm/icons/bookmark-x.mjs'
import BotIcon from '@lucide/vue/dist/esm/icons/bot.mjs'
import BoxIcon from '@lucide/vue/dist/esm/icons/box.mjs'
import BoxesIcon from '@lucide/vue/dist/esm/icons/boxes.mjs'
import BrainIcon from '@lucide/vue/dist/esm/icons/brain.mjs'
import BrainCircuitIcon from '@lucide/vue/dist/esm/icons/brain-circuit.mjs'
import BrainCogIcon from '@lucide/vue/dist/esm/icons/brain-cog.mjs'
import BrickWallIcon from '@lucide/vue/dist/esm/icons/brick-wall.mjs'
import BriefcaseIcon from '@lucide/vue/dist/esm/icons/briefcase.mjs'
import BrushIcon from '@lucide/vue/dist/esm/icons/brush.mjs'
import BrushCleaningIcon from '@lucide/vue/dist/esm/icons/brush-cleaning.mjs'
import BugIcon from '@lucide/vue/dist/esm/icons/bug.mjs'
import BugOffIcon from '@lucide/vue/dist/esm/icons/bug-off.mjs'
import BugPlayIcon from '@lucide/vue/dist/esm/icons/bug-play.mjs'
import BuildingIcon from '@lucide/vue/dist/esm/icons/building.mjs'
import Building2Icon from '@lucide/vue/dist/esm/icons/building-2.mjs'
import BusIcon from '@lucide/vue/dist/esm/icons/bus.mjs'
import BusFrontIcon from '@lucide/vue/dist/esm/icons/bus-front.mjs'
import CakeIcon from '@lucide/vue/dist/esm/icons/cake.mjs'
import CakeSliceIcon from '@lucide/vue/dist/esm/icons/cake-slice.mjs'
import CalendarIcon from '@lucide/vue/dist/esm/icons/calendar.mjs'
import CalendarCheckIcon from '@lucide/vue/dist/esm/icons/calendar-check.mjs'
import CalendarClockIcon from '@lucide/vue/dist/esm/icons/calendar-clock.mjs'
import CalendarDaysIcon from '@lucide/vue/dist/esm/icons/calendar-days.mjs'
import CalendarHeartIcon from '@lucide/vue/dist/esm/icons/calendar-heart.mjs'
import CalendarMinusIcon from '@lucide/vue/dist/esm/icons/calendar-minus.mjs'
import CalendarPlusIcon from '@lucide/vue/dist/esm/icons/calendar-plus.mjs'
import CalendarRangeIcon from '@lucide/vue/dist/esm/icons/calendar-range.mjs'
import CalendarSearchIcon from '@lucide/vue/dist/esm/icons/calendar-search.mjs'
import CalendarXIcon from '@lucide/vue/dist/esm/icons/calendar-x.mjs'
import CameraIcon from '@lucide/vue/dist/esm/icons/camera.mjs'
import CandyIcon from '@lucide/vue/dist/esm/icons/candy.mjs'
import CandyCaneIcon from '@lucide/vue/dist/esm/icons/candy-cane.mjs'
import CarIcon from '@lucide/vue/dist/esm/icons/car.mjs'
import CarFrontIcon from '@lucide/vue/dist/esm/icons/car-front.mjs'
import CarTaxiFrontIcon from '@lucide/vue/dist/esm/icons/car-taxi-front.mjs'
import CarrotIcon from '@lucide/vue/dist/esm/icons/carrot.mjs'
import CaseLowerIcon from '@lucide/vue/dist/esm/icons/case-lower.mjs'
import CaseSensitiveIcon from '@lucide/vue/dist/esm/icons/case-sensitive.mjs'
import CaseUpperIcon from '@lucide/vue/dist/esm/icons/case-upper.mjs'
import CastIcon from '@lucide/vue/dist/esm/icons/cast.mjs'
import CastleIcon from '@lucide/vue/dist/esm/icons/castle.mjs'
import CatIcon from '@lucide/vue/dist/esm/icons/cat.mjs'
import CheckIcon from '@lucide/vue/dist/esm/icons/check.mjs'
import CheckCircleIcon from '@lucide/vue/dist/esm/icons/circle-check-big.mjs'
import ChefHatIcon from '@lucide/vue/dist/esm/icons/chef-hat.mjs'
import CherryIcon from '@lucide/vue/dist/esm/icons/cherry.mjs'
import ChevronDownIcon from '@lucide/vue/dist/esm/icons/chevron-down.mjs'
import ChevronLeftIcon from '@lucide/vue/dist/esm/icons/chevron-left.mjs'
import ChevronRightIcon from '@lucide/vue/dist/esm/icons/chevron-right.mjs'
import ChevronUpIcon from '@lucide/vue/dist/esm/icons/chevron-up.mjs'
import ChevronsLeftIcon from '@lucide/vue/dist/esm/icons/chevrons-left.mjs'
import ChevronsRightIcon from '@lucide/vue/dist/esm/icons/chevrons-right.mjs'
import ChurchIcon from '@lucide/vue/dist/esm/icons/church.mjs'
import CigaretteIcon from '@lucide/vue/dist/esm/icons/cigarette.mjs'
import CigaretteOffIcon from '@lucide/vue/dist/esm/icons/cigarette-off.mjs'
import CircleIcon from '@lucide/vue/dist/esm/icons/circle.mjs'
import CheckCircle2Icon from '@lucide/vue/dist/esm/icons/circle-check.mjs'
import CircleDollarSignIcon from '@lucide/vue/dist/esm/icons/circle-dollar-sign.mjs'
import CircleDotIcon from '@lucide/vue/dist/esm/icons/circle-dot.mjs'
import CircleMinusIcon from '@lucide/vue/dist/esm/icons/circle-minus.mjs'
import CircleOffIcon from '@lucide/vue/dist/esm/icons/circle-off.mjs'
import CirclePlusIcon from '@lucide/vue/dist/esm/icons/circle-plus.mjs'
import CircleXIcon from '@lucide/vue/dist/esm/icons/circle-x.mjs'
import CircuitBoardIcon from '@lucide/vue/dist/esm/icons/circuit-board.mjs'
import CitrusIcon from '@lucide/vue/dist/esm/icons/citrus.mjs'
import ClapperboardIcon from '@lucide/vue/dist/esm/icons/clapperboard.mjs'
import ClipboardIcon from '@lucide/vue/dist/esm/icons/clipboard.mjs'
import ClipboardCheckIcon from '@lucide/vue/dist/esm/icons/clipboard-check.mjs'
import ClipboardCopyIcon from '@lucide/vue/dist/esm/icons/clipboard-copy.mjs'
import ClipboardListIcon from '@lucide/vue/dist/esm/icons/clipboard-list.mjs'
import ClipboardPasteIcon from '@lucide/vue/dist/esm/icons/clipboard-paste.mjs'
import ClipboardXIcon from '@lucide/vue/dist/esm/icons/clipboard-x.mjs'
import ClockIcon from '@lucide/vue/dist/esm/icons/clock.mjs'
import CloudIcon from '@lucide/vue/dist/esm/icons/cloud.mjs'
import CloudDownloadIcon from '@lucide/vue/dist/esm/icons/cloud-download.mjs'
import CloudDrizzleIcon from '@lucide/vue/dist/esm/icons/cloud-drizzle.mjs'
import CloudFogIcon from '@lucide/vue/dist/esm/icons/cloud-fog.mjs'
import CloudHailIcon from '@lucide/vue/dist/esm/icons/cloud-hail.mjs'
import CloudLightningIcon from '@lucide/vue/dist/esm/icons/cloud-lightning.mjs'
import CloudMoonIcon from '@lucide/vue/dist/esm/icons/cloud-moon.mjs'
import CloudOffIcon from '@lucide/vue/dist/esm/icons/cloud-off.mjs'
import CloudRainIcon from '@lucide/vue/dist/esm/icons/cloud-rain.mjs'
import CloudSnowIcon from '@lucide/vue/dist/esm/icons/cloud-snow.mjs'
import CloudSunIcon from '@lucide/vue/dist/esm/icons/cloud-sun.mjs'
import CloudUploadIcon from '@lucide/vue/dist/esm/icons/cloud-upload.mjs'
import ClubIcon from '@lucide/vue/dist/esm/icons/club.mjs'
import CodeIcon from '@lucide/vue/dist/esm/icons/code.mjs'
import CoffeeIcon from '@lucide/vue/dist/esm/icons/coffee.mjs'
import CogIcon from '@lucide/vue/dist/esm/icons/cog.mjs'
import ColumnsIcon from '@lucide/vue/dist/esm/icons/columns-2.mjs'
import Columns3Icon from '@lucide/vue/dist/esm/icons/columns-3.mjs'
import Columns4Icon from '@lucide/vue/dist/esm/icons/columns-4.mjs'
import CombineIcon from '@lucide/vue/dist/esm/icons/combine.mjs'
import CompassIcon from '@lucide/vue/dist/esm/icons/compass.mjs'
import ComponentIcon from '@lucide/vue/dist/esm/icons/component.mjs'
import ConstructionIcon from '@lucide/vue/dist/esm/icons/construction.mjs'
import ContactIcon from '@lucide/vue/dist/esm/icons/contact.mjs'
import Contact2Icon from '@lucide/vue/dist/esm/icons/contact-round.mjs'
import ContainerIcon from '@lucide/vue/dist/esm/icons/container.mjs'
import ContrastIcon from '@lucide/vue/dist/esm/icons/contrast.mjs'
import CookieIcon from '@lucide/vue/dist/esm/icons/cookie.mjs'
import CookingPotIcon from '@lucide/vue/dist/esm/icons/cooking-pot.mjs'
import CopyIcon from '@lucide/vue/dist/esm/icons/copy.mjs'
import CpuIcon from '@lucide/vue/dist/esm/icons/cpu.mjs'
import CreditCardIcon from '@lucide/vue/dist/esm/icons/credit-card.mjs'
import CropIcon from '@lucide/vue/dist/esm/icons/crop.mjs'
import CrossIcon from '@lucide/vue/dist/esm/icons/cross.mjs'
import CrosshairIcon from '@lucide/vue/dist/esm/icons/crosshair.mjs'
import CrownIcon from '@lucide/vue/dist/esm/icons/crown.mjs'
import DatabaseIcon from '@lucide/vue/dist/esm/icons/database.mjs'
import DiamondIcon from '@lucide/vue/dist/esm/icons/diamond.mjs'
import DiscIcon from '@lucide/vue/dist/esm/icons/disc.mjs'
import Disc2Icon from '@lucide/vue/dist/esm/icons/disc-2.mjs'
import DnaIcon from '@lucide/vue/dist/esm/icons/dna.mjs'
import DogIcon from '@lucide/vue/dist/esm/icons/dog.mjs'
import DollarSignIcon from '@lucide/vue/dist/esm/icons/dollar-sign.mjs'
import DoorClosedIcon from '@lucide/vue/dist/esm/icons/door-closed.mjs'
import DoorOpenIcon from '@lucide/vue/dist/esm/icons/door-open.mjs'
import DownloadIcon from '@lucide/vue/dist/esm/icons/download.mjs'
import DraftingCompassIcon from '@lucide/vue/dist/esm/icons/drafting-compass.mjs'
import DropletIcon from '@lucide/vue/dist/esm/icons/droplet.mjs'
import DropletsIcon from '@lucide/vue/dist/esm/icons/droplets.mjs'
import EarIcon from '@lucide/vue/dist/esm/icons/ear.mjs'
import EarOffIcon from '@lucide/vue/dist/esm/icons/ear-off.mjs'
import EarthIcon from '@lucide/vue/dist/esm/icons/earth.mjs'
import EclipseIcon from '@lucide/vue/dist/esm/icons/eclipse.mjs'
import EditIcon from '@lucide/vue/dist/esm/icons/square-pen.mjs'
import EggIcon from '@lucide/vue/dist/esm/icons/egg.mjs'
import EggFriedIcon from '@lucide/vue/dist/esm/icons/egg-fried.mjs'
import EraserIcon from '@lucide/vue/dist/esm/icons/eraser.mjs'
import EthernetPortIcon from '@lucide/vue/dist/esm/icons/ethernet-port.mjs'
import EuroIcon from '@lucide/vue/dist/esm/icons/euro.mjs'
import EvChargerIcon from '@lucide/vue/dist/esm/icons/ev-charger.mjs'
import ExpandIcon from '@lucide/vue/dist/esm/icons/expand.mjs'
import ExternalLinkIcon from '@lucide/vue/dist/esm/icons/external-link.mjs'
import EyeIcon from '@lucide/vue/dist/esm/icons/eye.mjs'
import EyeClosedIcon from '@lucide/vue/dist/esm/icons/eye-closed.mjs'
import EyeOffIcon from '@lucide/vue/dist/esm/icons/eye-off.mjs'
import FactoryIcon from '@lucide/vue/dist/esm/icons/factory.mjs'
import FanIcon from '@lucide/vue/dist/esm/icons/fan.mjs'
import FenceIcon from '@lucide/vue/dist/esm/icons/fence.mjs'
import FileIcon from '@lucide/vue/dist/esm/icons/file.mjs'
import FileAudioIcon from '@lucide/vue/dist/esm/icons/file-headphone.mjs'
import FileBoxIcon from '@lucide/vue/dist/esm/icons/file-box.mjs'
import FileCheckIcon from '@lucide/vue/dist/esm/icons/file-check.mjs'
import FileCodeIcon from '@lucide/vue/dist/esm/icons/file-code.mjs'
import FileDownIcon from '@lucide/vue/dist/esm/icons/file-down.mjs'
import FileImageIcon from '@lucide/vue/dist/esm/icons/file-image.mjs'
import FileInputIcon from '@lucide/vue/dist/esm/icons/file-input.mjs'
import FileBracesIcon from '@lucide/vue/dist/esm/icons/file-braces.mjs'
import FileMinusIcon from '@lucide/vue/dist/esm/icons/file-minus.mjs'
import FileOutputIcon from '@lucide/vue/dist/esm/icons/file-output.mjs'
import FileEditIcon from '@lucide/vue/dist/esm/icons/file-pen.mjs'
import FilePlusIcon from '@lucide/vue/dist/esm/icons/file-plus.mjs'
import FileQuestionIcon from '@lucide/vue/dist/esm/icons/file-question-mark.mjs'
import FileSearchIcon from '@lucide/vue/dist/esm/icons/file-search.mjs'
import FilePenLineIcon from '@lucide/vue/dist/esm/icons/file-pen-line.mjs'
import FileSlidersIcon from '@lucide/vue/dist/esm/icons/file-sliders.mjs'
import FileSpreadsheetIcon from '@lucide/vue/dist/esm/icons/file-spreadsheet.mjs'
import FileStackIcon from '@lucide/vue/dist/esm/icons/file-stack.mjs'
import FileSymlinkIcon from '@lucide/vue/dist/esm/icons/file-symlink.mjs'
import FileTextIcon from '@lucide/vue/dist/esm/icons/file-text.mjs'
import FileTypeIcon from '@lucide/vue/dist/esm/icons/file-type.mjs'
import FileType2Icon from '@lucide/vue/dist/esm/icons/file-type-corner.mjs'
import FileUpIcon from '@lucide/vue/dist/esm/icons/file-up.mjs'
import FileUserIcon from '@lucide/vue/dist/esm/icons/file-user.mjs'
import FilePlayIcon from '@lucide/vue/dist/esm/icons/file-play.mjs'
import FileVolumeIcon from '@lucide/vue/dist/esm/icons/file-volume.mjs'
import FileExclamationPointIcon from '@lucide/vue/dist/esm/icons/file-exclamation-point.mjs'
import FileXIcon from '@lucide/vue/dist/esm/icons/file-x.mjs'
import FilesIcon from '@lucide/vue/dist/esm/icons/files.mjs'
import FilmIcon from '@lucide/vue/dist/esm/icons/film.mjs'
import FilterIcon from '@lucide/vue/dist/esm/icons/funnel.mjs'
import FingerprintIcon from '@lucide/vue/dist/esm/icons/fingerprint-pattern.mjs'
import FireExtinguisherIcon from '@lucide/vue/dist/esm/icons/fire-extinguisher.mjs'
import FishIcon from '@lucide/vue/dist/esm/icons/fish.mjs'
import FishOffIcon from '@lucide/vue/dist/esm/icons/fish-off.mjs'
import FlagIcon from '@lucide/vue/dist/esm/icons/flag.mjs'
import FlagOffIcon from '@lucide/vue/dist/esm/icons/flag-off.mjs'
import FlameIcon from '@lucide/vue/dist/esm/icons/flame.mjs'
import FlashlightIcon from '@lucide/vue/dist/esm/icons/flashlight.mjs'
import FlaskConicalIcon from '@lucide/vue/dist/esm/icons/flask-conical.mjs'
import FlipHorizontalIcon from '@lucide/vue/dist/esm/icons/square-centerline-dashed-horizontal.mjs'
import FlipVerticalIcon from '@lucide/vue/dist/esm/icons/square-centerline-dashed-vertical.mjs'
import FlowerIcon from '@lucide/vue/dist/esm/icons/flower.mjs'
import FocusIcon from '@lucide/vue/dist/esm/icons/focus.mjs'
import FolderIcon from '@lucide/vue/dist/esm/icons/folder.mjs'
import FolderArchiveIcon from '@lucide/vue/dist/esm/icons/folder-archive.mjs'
import FolderCheckIcon from '@lucide/vue/dist/esm/icons/folder-check.mjs'
import FolderCogIcon from '@lucide/vue/dist/esm/icons/folder-cog.mjs'
import FolderDotIcon from '@lucide/vue/dist/esm/icons/folder-dot.mjs'
import FolderDownIcon from '@lucide/vue/dist/esm/icons/folder-down.mjs'
import FolderGitIcon from '@lucide/vue/dist/esm/icons/folder-git.mjs'
import FolderGit2Icon from '@lucide/vue/dist/esm/icons/folder-git-2.mjs'
import FolderHeartIcon from '@lucide/vue/dist/esm/icons/folder-heart.mjs'
import FolderInputIcon from '@lucide/vue/dist/esm/icons/folder-input.mjs'
import FolderKanbanIcon from '@lucide/vue/dist/esm/icons/folder-kanban.mjs'
import FolderKeyIcon from '@lucide/vue/dist/esm/icons/folder-key.mjs'
import FolderLockIcon from '@lucide/vue/dist/esm/icons/folder-lock.mjs'
import FolderMinusIcon from '@lucide/vue/dist/esm/icons/folder-minus.mjs'
import FolderOpenIcon from '@lucide/vue/dist/esm/icons/folder-open.mjs'
import FolderOutputIcon from '@lucide/vue/dist/esm/icons/folder-output.mjs'
import FolderEditIcon from '@lucide/vue/dist/esm/icons/folder-pen.mjs'
import FolderPlusIcon from '@lucide/vue/dist/esm/icons/folder-plus.mjs'
import FolderSearchIcon from '@lucide/vue/dist/esm/icons/folder-search.mjs'
import FolderSyncIcon from '@lucide/vue/dist/esm/icons/folder-sync.mjs'
import FolderTreeIcon from '@lucide/vue/dist/esm/icons/folder-tree.mjs'
import FolderUpIcon from '@lucide/vue/dist/esm/icons/folder-up.mjs'
import FolderXIcon from '@lucide/vue/dist/esm/icons/folder-x.mjs'
import FootprintsIcon from '@lucide/vue/dist/esm/icons/footprints.mjs'
import ForkliftIcon from '@lucide/vue/dist/esm/icons/forklift.mjs'
import ForwardIcon from '@lucide/vue/dist/esm/icons/forward.mjs'
import FaceSlightlyFrowningIcon from '@lucide/vue/dist/esm/icons/face-slightly-frowning.mjs'
import FuelIcon from '@lucide/vue/dist/esm/icons/fuel.mjs'
import FullscreenIcon from '@lucide/vue/dist/esm/icons/fullscreen.mjs'
import GalleryHorizontalIcon from '@lucide/vue/dist/esm/icons/gallery-horizontal.mjs'
import GalleryThumbnailsIcon from '@lucide/vue/dist/esm/icons/gallery-thumbnails.mjs'
import GalleryVerticalIcon from '@lucide/vue/dist/esm/icons/gallery-vertical.mjs'
import GamepadIcon from '@lucide/vue/dist/esm/icons/gamepad.mjs'
import Gamepad2Icon from '@lucide/vue/dist/esm/icons/gamepad-2.mjs'
import GavelIcon from '@lucide/vue/dist/esm/icons/gavel.mjs'
import GemIcon from '@lucide/vue/dist/esm/icons/gem.mjs'
import GiftIcon from '@lucide/vue/dist/esm/icons/gift.mjs'
import GitBranchIcon from '@lucide/vue/dist/esm/icons/git-branch.mjs'
import GitCommitIcon from '@lucide/vue/dist/esm/icons/git-commit-horizontal.mjs'
import GitForkIcon from '@lucide/vue/dist/esm/icons/git-fork.mjs'
import GitMergeIcon from '@lucide/vue/dist/esm/icons/git-merge.mjs'
import GitPullRequestIcon from '@lucide/vue/dist/esm/icons/git-pull-request.mjs'
import GlassWaterIcon from '@lucide/vue/dist/esm/icons/glass-water.mjs'
import GlassesIcon from '@lucide/vue/dist/esm/icons/glasses.mjs'
import GlobeIcon from '@lucide/vue/dist/esm/icons/globe.mjs'
import GlobeLockIcon from '@lucide/vue/dist/esm/icons/globe-lock.mjs'
import GraduationCapIcon from '@lucide/vue/dist/esm/icons/graduation-cap.mjs'
import GrapeIcon from '@lucide/vue/dist/esm/icons/grape.mjs'
import GridIcon from '@lucide/vue/dist/esm/icons/grid-3x3.mjs'
import GripVerticalIcon from '@lucide/vue/dist/esm/icons/grip-vertical.mjs'
import HamIcon from '@lucide/vue/dist/esm/icons/ham.mjs'
import HammerIcon from '@lucide/vue/dist/esm/icons/hammer.mjs'
import HandIcon from '@lucide/vue/dist/esm/icons/hand.mjs'
import HandCoinsIcon from '@lucide/vue/dist/esm/icons/hand-coins.mjs'
import HandHeartIcon from '@lucide/vue/dist/esm/icons/hand-heart.mjs'
import HandHelpingIcon from '@lucide/vue/dist/esm/icons/hand-helping.mjs'
import HandMetalIcon from '@lucide/vue/dist/esm/icons/hand-metal.mjs'
import HandPlatterIcon from '@lucide/vue/dist/esm/icons/hand-platter.mjs'
import HandshakeIcon from '@lucide/vue/dist/esm/icons/handshake.mjs'
import HardDriveIcon from '@lucide/vue/dist/esm/icons/hard-drive.mjs'
import HardDriveDownloadIcon from '@lucide/vue/dist/esm/icons/hard-drive-download.mjs'
import HardDriveUploadIcon from '@lucide/vue/dist/esm/icons/hard-drive-upload.mjs'
import HardHatIcon from '@lucide/vue/dist/esm/icons/hard-hat.mjs'
import HashIcon from '@lucide/vue/dist/esm/icons/hash.mjs'
import HeadingIcon from '@lucide/vue/dist/esm/icons/heading.mjs'
import HeadphonesIcon from '@lucide/vue/dist/esm/icons/headphones.mjs'
import HeartIcon from '@lucide/vue/dist/esm/icons/heart.mjs'
import HeartHandshakeIcon from '@lucide/vue/dist/esm/icons/heart-handshake.mjs'
import HeartPulseIcon from '@lucide/vue/dist/esm/icons/heart-pulse.mjs'
import HeaterIcon from '@lucide/vue/dist/esm/icons/heater.mjs'
import HelicopterIcon from '@lucide/vue/dist/esm/icons/helicopter.mjs'
import CircleHelpIcon from '@lucide/vue/dist/esm/icons/circle-question-mark.mjs'
import HexagonIcon from '@lucide/vue/dist/esm/icons/hexagon.mjs'
import HighlighterIcon from '@lucide/vue/dist/esm/icons/highlighter.mjs'
import HistoryIcon from '@lucide/vue/dist/esm/icons/rotate-ccw-clock.mjs'
import HomeIcon from '@lucide/vue/dist/esm/icons/house.mjs'
import HospitalIcon from '@lucide/vue/dist/esm/icons/hospital.mjs'
import HotelIcon from '@lucide/vue/dist/esm/icons/hotel.mjs'
import HourglassIcon from '@lucide/vue/dist/esm/icons/hourglass.mjs'
import HouseHeartIcon from '@lucide/vue/dist/esm/icons/house-heart.mjs'
import HousePlugIcon from '@lucide/vue/dist/esm/icons/house-plug.mjs'
import HousePlusIcon from '@lucide/vue/dist/esm/icons/house-plus.mjs'
import HouseWifiIcon from '@lucide/vue/dist/esm/icons/house-wifi.mjs'
import IceCream2Icon from '@lucide/vue/dist/esm/icons/ice-cream-bowl.mjs'
import IceCreamIcon from '@lucide/vue/dist/esm/icons/ice-cream-cone.mjs'
import IdCardIcon from '@lucide/vue/dist/esm/icons/id-card.mjs'
import ImageIcon from '@lucide/vue/dist/esm/icons/image.mjs'
import ImageDownIcon from '@lucide/vue/dist/esm/icons/image-down.mjs'
import ImageMinusIcon from '@lucide/vue/dist/esm/icons/image-minus.mjs'
import ImageOffIcon from '@lucide/vue/dist/esm/icons/image-off.mjs'
import ImagePlayIcon from '@lucide/vue/dist/esm/icons/image-play.mjs'
import ImagePlusIcon from '@lucide/vue/dist/esm/icons/image-plus.mjs'
import ImageUpIcon from '@lucide/vue/dist/esm/icons/image-up.mjs'
import ImagesIcon from '@lucide/vue/dist/esm/icons/images.mjs'
import InboxIcon from '@lucide/vue/dist/esm/icons/inbox.mjs'
import InfinityIcon from '@lucide/vue/dist/esm/icons/infinity.mjs'
import InfoIcon from '@lucide/vue/dist/esm/icons/info.mjs'
import ItalicIcon from '@lucide/vue/dist/esm/icons/italic.mjs'
import JoystickIcon from '@lucide/vue/dist/esm/icons/joystick.mjs'
import KanbanIcon from '@lucide/vue/dist/esm/icons/kanban.mjs'
import KeyIcon from '@lucide/vue/dist/esm/icons/key.mjs'
import KeyRoundIcon from '@lucide/vue/dist/esm/icons/key-round.mjs'
import KeySquareIcon from '@lucide/vue/dist/esm/icons/key-square.mjs'
import KeyboardIcon from '@lucide/vue/dist/esm/icons/keyboard.mjs'
import LampIcon from '@lucide/vue/dist/esm/icons/lamp.mjs'
import LandmarkIcon from '@lucide/vue/dist/esm/icons/landmark.mjs'
import LanguagesIcon from '@lucide/vue/dist/esm/icons/languages.mjs'
import LaptopIcon from '@lucide/vue/dist/esm/icons/laptop.mjs'
import FaceGrinningIcon from '@lucide/vue/dist/esm/icons/face-grinning.mjs'
import LayersIcon from '@lucide/vue/dist/esm/icons/layers.mjs'
import LayoutDashboardIcon from '@lucide/vue/dist/esm/icons/layout-dashboard.mjs'
import LayoutGridIcon from '@lucide/vue/dist/esm/icons/layout-grid.mjs'
import LayoutListIcon from '@lucide/vue/dist/esm/icons/layout-list.mjs'
import LayoutPanelLeftIcon from '@lucide/vue/dist/esm/icons/layout-panel-left.mjs'
import LayoutPanelTopIcon from '@lucide/vue/dist/esm/icons/layout-panel-top.mjs'
import LayoutTemplateIcon from '@lucide/vue/dist/esm/icons/layout-template.mjs'
import LeafIcon from '@lucide/vue/dist/esm/icons/leaf.mjs'
import LibraryIcon from '@lucide/vue/dist/esm/icons/library.mjs'
import LibraryBigIcon from '@lucide/vue/dist/esm/icons/library-big.mjs'
import LifeBuoyIcon from '@lucide/vue/dist/esm/icons/life-buoy.mjs'
import LightbulbIcon from '@lucide/vue/dist/esm/icons/lightbulb.mjs'
import ChartLineIcon from '@lucide/vue/dist/esm/icons/chart-line.mjs'
import LinkIcon from '@lucide/vue/dist/esm/icons/link.mjs'
import Link2Icon from '@lucide/vue/dist/esm/icons/link-2.mjs'
import ListIcon from '@lucide/vue/dist/esm/icons/list.mjs'
import ListChecksIcon from '@lucide/vue/dist/esm/icons/list-checks.mjs'
import ListCollapseIcon from '@lucide/vue/dist/esm/icons/list-collapse.mjs'
import ListEndIcon from '@lucide/vue/dist/esm/icons/list-end.mjs'
import ListFilterIcon from '@lucide/vue/dist/esm/icons/list-filter.mjs'
import ListMinusIcon from '@lucide/vue/dist/esm/icons/list-minus.mjs'
import ListOrderedIcon from '@lucide/vue/dist/esm/icons/list-ordered.mjs'
import ListPlusIcon from '@lucide/vue/dist/esm/icons/list-plus.mjs'
import ListRestartIcon from '@lucide/vue/dist/esm/icons/list-restart.mjs'
import ListStartIcon from '@lucide/vue/dist/esm/icons/list-start.mjs'
import ListTodoIcon from '@lucide/vue/dist/esm/icons/list-todo.mjs'
import ListTreeIcon from '@lucide/vue/dist/esm/icons/list-tree.mjs'
import ListXIcon from '@lucide/vue/dist/esm/icons/list-x.mjs'
import Loader2Icon from '@lucide/vue/dist/esm/icons/loader-circle.mjs'
import LocateIcon from '@lucide/vue/dist/esm/icons/locate.mjs'
import LocateFixedIcon from '@lucide/vue/dist/esm/icons/locate-fixed.mjs'
import LocateOffIcon from '@lucide/vue/dist/esm/icons/locate-off.mjs'
import LockIcon from '@lucide/vue/dist/esm/icons/lock.mjs'
import LockKeyholeIcon from '@lucide/vue/dist/esm/icons/lock-keyhole.mjs'
import LockOpenIcon from '@lucide/vue/dist/esm/icons/lock-open.mjs'
import LogInIcon from '@lucide/vue/dist/esm/icons/log-in.mjs'
import LogOutIcon from '@lucide/vue/dist/esm/icons/log-out.mjs'
import LollipopIcon from '@lucide/vue/dist/esm/icons/lollipop.mjs'
import LucideMagnetIcon from '@lucide/vue/dist/esm/icons/magnet.mjs'
import LucideMailIcon from '@lucide/vue/dist/esm/icons/mail.mjs'
import LucideMailCheckIcon from '@lucide/vue/dist/esm/icons/mail-check.mjs'
import LucideMailMinusIcon from '@lucide/vue/dist/esm/icons/mail-minus.mjs'
import LucideMailOpenIcon from '@lucide/vue/dist/esm/icons/mail-open.mjs'
import LucideMailPlusIcon from '@lucide/vue/dist/esm/icons/mail-plus.mjs'
import LucideMailQuestionIcon from '@lucide/vue/dist/esm/icons/mail-question-mark.mjs'
import LucideMailWarningIcon from '@lucide/vue/dist/esm/icons/mail-warning.mjs'
import LucideMailXIcon from '@lucide/vue/dist/esm/icons/mail-x.mjs'
import LucideMapIcon from '@lucide/vue/dist/esm/icons/map.mjs'
import LucideMapPinIcon from '@lucide/vue/dist/esm/icons/map-pin.mjs'
import LucideMapPinOffIcon from '@lucide/vue/dist/esm/icons/map-pin-off.mjs'
import LucideMapPinnedIcon from '@lucide/vue/dist/esm/icons/map-pinned.mjs'
import LucideMaximizeIcon from '@lucide/vue/dist/esm/icons/maximize.mjs'
import LucideMaximize2Icon from '@lucide/vue/dist/esm/icons/maximize-2.mjs'
import LucideMedalIcon from '@lucide/vue/dist/esm/icons/medal.mjs'
import LucideMegaphoneIcon from '@lucide/vue/dist/esm/icons/megaphone.mjs'
import FaceNeutralIcon from '@lucide/vue/dist/esm/icons/face-neutral.mjs'
import LucideMenuIcon from '@lucide/vue/dist/esm/icons/menu.mjs'
import LucideMergeIcon from '@lucide/vue/dist/esm/icons/merge.mjs'
import LucideMessageCircleIcon from '@lucide/vue/dist/esm/icons/message-circle.mjs'
import LucideMessageSquareIcon from '@lucide/vue/dist/esm/icons/message-square.mjs'
import LucideMessagesSquareIcon from '@lucide/vue/dist/esm/icons/messages-square.mjs'
import LucideMicIcon from '@lucide/vue/dist/esm/icons/mic.mjs'
import LucideMic2Icon from '@lucide/vue/dist/esm/icons/mic-vocal.mjs'
import LucideMicOffIcon from '@lucide/vue/dist/esm/icons/mic-off.mjs'
import LucideMicroscopeIcon from '@lucide/vue/dist/esm/icons/microscope.mjs'
import LucideMicrowaveIcon from '@lucide/vue/dist/esm/icons/microwave.mjs'
import LucideMilestoneIcon from '@lucide/vue/dist/esm/icons/milestone.mjs'
import LucideMilkIcon from '@lucide/vue/dist/esm/icons/milk.mjs'
import LucideMinimizeIcon from '@lucide/vue/dist/esm/icons/minimize.mjs'
import LucideMinimize2Icon from '@lucide/vue/dist/esm/icons/minimize-2.mjs'
import LucideMinusIcon from '@lucide/vue/dist/esm/icons/minus.mjs'
import LucideMonitorIcon from '@lucide/vue/dist/esm/icons/monitor.mjs'
import LucideMonitorPlayIcon from '@lucide/vue/dist/esm/icons/monitor-play.mjs'
import LucideMonitorSmartphoneIcon from '@lucide/vue/dist/esm/icons/monitor-smartphone.mjs'
import LucideMonitorSpeakerIcon from '@lucide/vue/dist/esm/icons/monitor-speaker.mjs'
import LucideMoonIcon from '@lucide/vue/dist/esm/icons/moon.mjs'
import LucideMoonStarIcon from '@lucide/vue/dist/esm/icons/moon-star.mjs'
import EllipsisIcon from '@lucide/vue/dist/esm/icons/ellipsis.mjs'
import EllipsisVerticalIcon from '@lucide/vue/dist/esm/icons/ellipsis-vertical.mjs'
import LucideMountainIcon from '@lucide/vue/dist/esm/icons/mountain.mjs'
import LucideMouseIcon from '@lucide/vue/dist/esm/icons/mouse.mjs'
import LucideMousePointerIcon from '@lucide/vue/dist/esm/icons/mouse-pointer.mjs'
import LucideMousePointer2Icon from '@lucide/vue/dist/esm/icons/mouse-pointer-2.mjs'
import LucideMoveIcon from '@lucide/vue/dist/esm/icons/move.mjs'
import LucideMove3DIcon from '@lucide/vue/dist/esm/icons/move-3d.mjs'
import LucideMusicIcon from '@lucide/vue/dist/esm/icons/music.mjs'
import LucideMusic2Icon from '@lucide/vue/dist/esm/icons/music-2.mjs'
import LucideMusic3Icon from '@lucide/vue/dist/esm/icons/music-3.mjs'
import LucideMusic4Icon from '@lucide/vue/dist/esm/icons/music-4.mjs'
import LucideNavigationIcon from '@lucide/vue/dist/esm/icons/navigation.mjs'
import LucideNavigationOffIcon from '@lucide/vue/dist/esm/icons/navigation-off.mjs'
import LucideNetworkIcon from '@lucide/vue/dist/esm/icons/network.mjs'
import LucideNewspaperIcon from '@lucide/vue/dist/esm/icons/newspaper.mjs'
import LucideNfcIcon from '@lucide/vue/dist/esm/icons/nfc.mjs'
import LucideNotebookIcon from '@lucide/vue/dist/esm/icons/notebook.mjs'
import LucideNotebookPenIcon from '@lucide/vue/dist/esm/icons/notebook-pen.mjs'
import LucideNotebookTabsIcon from '@lucide/vue/dist/esm/icons/notebook-tabs.mjs'
import LucideNotebookTextIcon from '@lucide/vue/dist/esm/icons/notebook-text.mjs'
import LucideNotepadTextIcon from '@lucide/vue/dist/esm/icons/notepad-text.mjs'
import LucideNutIcon from '@lucide/vue/dist/esm/icons/nut.mjs'
import LucideOctagonIcon from '@lucide/vue/dist/esm/icons/octagon.mjs'
import AlertOctagonIcon from '@lucide/vue/dist/esm/icons/octagon-alert.mjs'
import LucideOrbitIcon from '@lucide/vue/dist/esm/icons/orbit.mjs'
import LucidePackageIcon from '@lucide/vue/dist/esm/icons/package.mjs'
import LucidePackage2Icon from '@lucide/vue/dist/esm/icons/package-2.mjs'
import LucidePackageCheckIcon from '@lucide/vue/dist/esm/icons/package-check.mjs'
import LucidePackageMinusIcon from '@lucide/vue/dist/esm/icons/package-minus.mjs'
import LucidePackageOpenIcon from '@lucide/vue/dist/esm/icons/package-open.mjs'
import LucidePackagePlusIcon from '@lucide/vue/dist/esm/icons/package-plus.mjs'
import LucidePackageSearchIcon from '@lucide/vue/dist/esm/icons/package-search.mjs'
import LucidePackageXIcon from '@lucide/vue/dist/esm/icons/package-x.mjs'
import LucidePaintbrushIcon from '@lucide/vue/dist/esm/icons/paintbrush.mjs'
import LucidePaletteIcon from '@lucide/vue/dist/esm/icons/palette.mjs'
import LucidePanelBottomIcon from '@lucide/vue/dist/esm/icons/panel-bottom.mjs'
import LucidePanelLeftIcon from '@lucide/vue/dist/esm/icons/panel-left.mjs'
import LucidePanelLeftCloseIcon from '@lucide/vue/dist/esm/icons/panel-left-close.mjs'
import LucidePanelLeftOpenIcon from '@lucide/vue/dist/esm/icons/panel-left-open.mjs'
import LucidePanelRightIcon from '@lucide/vue/dist/esm/icons/panel-right.mjs'
import LucidePanelTopIcon from '@lucide/vue/dist/esm/icons/panel-top.mjs'
import LucidePaperclipIcon from '@lucide/vue/dist/esm/icons/paperclip.mjs'
import LucideParkingMeterIcon from '@lucide/vue/dist/esm/icons/parking-meter.mjs'
import LucidePauseIcon from '@lucide/vue/dist/esm/icons/pause.mjs'
import LucidePawPrintIcon from '@lucide/vue/dist/esm/icons/paw-print.mjs'
import Edit3Icon from '@lucide/vue/dist/esm/icons/pen-line.mjs'
import LucidePenToolIcon from '@lucide/vue/dist/esm/icons/pen-tool.mjs'
import LucidePencilIcon from '@lucide/vue/dist/esm/icons/pencil.mjs'
import LucidePencilLineIcon from '@lucide/vue/dist/esm/icons/pencil-line.mjs'
import LucidePencilRulerIcon from '@lucide/vue/dist/esm/icons/pencil-ruler.mjs'
import LucidePentagonIcon from '@lucide/vue/dist/esm/icons/pentagon.mjs'
import LucidePercentIcon from '@lucide/vue/dist/esm/icons/percent.mjs'
import LucidePhoneIcon from '@lucide/vue/dist/esm/icons/phone.mjs'
import LucidePhoneCallIcon from '@lucide/vue/dist/esm/icons/phone-call.mjs'
import LucidePhoneForwardedIcon from '@lucide/vue/dist/esm/icons/phone-forwarded.mjs'
import LucidePhoneIncomingIcon from '@lucide/vue/dist/esm/icons/phone-incoming.mjs'
import LucidePhoneMissedIcon from '@lucide/vue/dist/esm/icons/phone-missed.mjs'
import LucidePhoneOffIcon from '@lucide/vue/dist/esm/icons/phone-off.mjs'
import LucidePhoneOutgoingIcon from '@lucide/vue/dist/esm/icons/phone-outgoing.mjs'
import LucidePiIcon from '@lucide/vue/dist/esm/icons/pi.mjs'
import LucidePickaxeIcon from '@lucide/vue/dist/esm/icons/pickaxe.mjs'
import LucidePictureInPictureIcon from '@lucide/vue/dist/esm/icons/picture-in-picture.mjs'
import LucidePictureInPicture2Icon from '@lucide/vue/dist/esm/icons/picture-in-picture-2.mjs'
import ChartPieIcon from '@lucide/vue/dist/esm/icons/chart-pie.mjs'
import LucidePiggyBankIcon from '@lucide/vue/dist/esm/icons/piggy-bank.mjs'
import LucidePilcrowIcon from '@lucide/vue/dist/esm/icons/pilcrow.mjs'
import LucidePillIcon from '@lucide/vue/dist/esm/icons/pill.mjs'
import LucidePillBottleIcon from '@lucide/vue/dist/esm/icons/pill-bottle.mjs'
import LucidePinIcon from '@lucide/vue/dist/esm/icons/pin.mjs'
import LucidePinOffIcon from '@lucide/vue/dist/esm/icons/pin-off.mjs'
import LucidePizzaIcon from '@lucide/vue/dist/esm/icons/pizza.mjs'
import LucidePlaneIcon from '@lucide/vue/dist/esm/icons/plane.mjs'
import LucidePlaneLandingIcon from '@lucide/vue/dist/esm/icons/plane-landing.mjs'
import LucidePlaneTakeoffIcon from '@lucide/vue/dist/esm/icons/plane-takeoff.mjs'
import LucidePlayIcon from '@lucide/vue/dist/esm/icons/play.mjs'
import LucidePlugIcon from '@lucide/vue/dist/esm/icons/plug.mjs'
import LucidePlugZapIcon from '@lucide/vue/dist/esm/icons/plug-zap.mjs'
import LucidePlusIcon from '@lucide/vue/dist/esm/icons/plus.mjs'
import LucidePopcornIcon from '@lucide/vue/dist/esm/icons/popcorn.mjs'
import LucidePowerIcon from '@lucide/vue/dist/esm/icons/power.mjs'
import LucidePresentationIcon from '@lucide/vue/dist/esm/icons/presentation.mjs'
import LucidePrinterIcon from '@lucide/vue/dist/esm/icons/printer.mjs'
import LucideProjectorIcon from '@lucide/vue/dist/esm/icons/projector.mjs'
import LucidePuzzleIcon from '@lucide/vue/dist/esm/icons/puzzle.mjs'
import LucideQrCodeIcon from '@lucide/vue/dist/esm/icons/qr-code.mjs'
import LucideQuoteIcon from '@lucide/vue/dist/esm/icons/quote.mjs'
import LucideRabbitIcon from '@lucide/vue/dist/esm/icons/rabbit.mjs'
import LucideRadarIcon from '@lucide/vue/dist/esm/icons/radar.mjs'
import LucideRadioIcon from '@lucide/vue/dist/esm/icons/radio.mjs'
import LucideRadioTowerIcon from '@lucide/vue/dist/esm/icons/radio-tower.mjs'
import LucideRatIcon from '@lucide/vue/dist/esm/icons/rat.mjs'
import LucideRatioIcon from '@lucide/vue/dist/esm/icons/ratio.mjs'
import LucideReceiptIcon from '@lucide/vue/dist/esm/icons/receipt.mjs'
import LucideReceiptCentIcon from '@lucide/vue/dist/esm/icons/receipt-cent.mjs'
import LucideReceiptTextIcon from '@lucide/vue/dist/esm/icons/receipt-text.mjs'
import LucideRecycleIcon from '@lucide/vue/dist/esm/icons/recycle.mjs'
import LucideRedoIcon from '@lucide/vue/dist/esm/icons/redo.mjs'
import LucideRefreshCcwIcon from '@lucide/vue/dist/esm/icons/refresh-ccw.mjs'
import LucideRefreshCwIcon from '@lucide/vue/dist/esm/icons/refresh-cw.mjs'
import LucideRefreshCwOffIcon from '@lucide/vue/dist/esm/icons/refresh-cw-off.mjs'
import LucideRefrigeratorIcon from '@lucide/vue/dist/esm/icons/refrigerator.mjs'
import LucideRemoveFormattingIcon from '@lucide/vue/dist/esm/icons/remove-formatting.mjs'
import LucideReplyIcon from '@lucide/vue/dist/esm/icons/reply.mjs'
import LucideReplyAllIcon from '@lucide/vue/dist/esm/icons/reply-all.mjs'
import LucideRocketIcon from '@lucide/vue/dist/esm/icons/rocket.mjs'
import LucideRockingChairIcon from '@lucide/vue/dist/esm/icons/rocking-chair.mjs'
import LucideRotate3DIcon from '@lucide/vue/dist/esm/icons/rotate-3d.mjs'
import LucideRotateCcwIcon from '@lucide/vue/dist/esm/icons/rotate-ccw.mjs'
import LucideRouteIcon from '@lucide/vue/dist/esm/icons/route.mjs'
import LucideRouteOffIcon from '@lucide/vue/dist/esm/icons/route-off.mjs'
import LucideRouterIcon from '@lucide/vue/dist/esm/icons/router.mjs'
import LucideRowsIcon from '@lucide/vue/dist/esm/icons/rows-2.mjs'
import LucidePanelsTopBottomIcon from '@lucide/vue/dist/esm/icons/rows-3.mjs'
import LucideRows4Icon from '@lucide/vue/dist/esm/icons/rows-4.mjs'
import LucideRssIcon from '@lucide/vue/dist/esm/icons/rss.mjs'
import LucideRulerIcon from '@lucide/vue/dist/esm/icons/ruler.mjs'
import LucideSailboatIcon from '@lucide/vue/dist/esm/icons/sailboat.mjs'
import LucideSaladIcon from '@lucide/vue/dist/esm/icons/salad.mjs'
import LucideSandwichIcon from '@lucide/vue/dist/esm/icons/sandwich.mjs'
import LucideSatelliteIcon from '@lucide/vue/dist/esm/icons/satellite.mjs'
import LucideSatelliteDishIcon from '@lucide/vue/dist/esm/icons/satellite-dish.mjs'
import LucideSaveIcon from '@lucide/vue/dist/esm/icons/save.mjs'
import LucideScaleIcon from '@lucide/vue/dist/esm/icons/scale.mjs'
import LucideScanIcon from '@lucide/vue/dist/esm/icons/scan.mjs'
import LucideScanBarcodeIcon from '@lucide/vue/dist/esm/icons/scan-barcode.mjs'
import LucideScanEyeIcon from '@lucide/vue/dist/esm/icons/scan-eye.mjs'
import LucideScanFaceIcon from '@lucide/vue/dist/esm/icons/scan-face.mjs'
import LucideScanHeartIcon from '@lucide/vue/dist/esm/icons/scan-heart.mjs'
import LucideScanLineIcon from '@lucide/vue/dist/esm/icons/scan-line.mjs'
import LucideScanSearchIcon from '@lucide/vue/dist/esm/icons/scan-search.mjs'
import LucideScanTextIcon from '@lucide/vue/dist/esm/icons/scan-text.mjs'
import LucideSchoolIcon from '@lucide/vue/dist/esm/icons/school.mjs'
import LucideScissorsIcon from '@lucide/vue/dist/esm/icons/scissors.mjs'
import LucideScreenShareIcon from '@lucide/vue/dist/esm/icons/screen-share.mjs'
import LucideScreenShareOffIcon from '@lucide/vue/dist/esm/icons/screen-share-off.mjs'
import LucideScrollIcon from '@lucide/vue/dist/esm/icons/scroll.mjs'
import LucideScrollTextIcon from '@lucide/vue/dist/esm/icons/scroll-text.mjs'
import LucideSearchIcon from '@lucide/vue/dist/esm/icons/search.mjs'
import LucideSendIcon from '@lucide/vue/dist/esm/icons/send.mjs'
import LucideSendHorizonalIcon from '@lucide/vue/dist/esm/icons/send-horizontal.mjs'
import LucideServerIcon from '@lucide/vue/dist/esm/icons/server.mjs'
import LucideServerCogIcon from '@lucide/vue/dist/esm/icons/server-cog.mjs'
import LucideServerCrashIcon from '@lucide/vue/dist/esm/icons/server-crash.mjs'
import LucideServerOffIcon from '@lucide/vue/dist/esm/icons/server-off.mjs'
import LucideSettingsIcon from '@lucide/vue/dist/esm/icons/settings.mjs'
import LucideShapesIcon from '@lucide/vue/dist/esm/icons/shapes.mjs'
import LucideShareIcon from '@lucide/vue/dist/esm/icons/share.mjs'
import LucideShare2Icon from '@lucide/vue/dist/esm/icons/share-2.mjs'
import LucideSheetIcon from '@lucide/vue/dist/esm/icons/sheet.mjs'
import LucideShellIcon from '@lucide/vue/dist/esm/icons/shell.mjs'
import LucideShieldIcon from '@lucide/vue/dist/esm/icons/shield.mjs'
import LucideShieldAlertIcon from '@lucide/vue/dist/esm/icons/shield-alert.mjs'
import LucideShieldBanIcon from '@lucide/vue/dist/esm/icons/shield-ban.mjs'
import LucideShieldCheckIcon from '@lucide/vue/dist/esm/icons/shield-check.mjs'
import LucideShieldHalfIcon from '@lucide/vue/dist/esm/icons/shield-half.mjs'
import LucideShieldQuestionIcon from '@lucide/vue/dist/esm/icons/shield-question-mark.mjs'
import LucideShieldCloseIcon from '@lucide/vue/dist/esm/icons/shield-x.mjs'
import LucideShipIcon from '@lucide/vue/dist/esm/icons/ship.mjs'
import LucideShipWheelIcon from '@lucide/vue/dist/esm/icons/ship-wheel.mjs'
import LucideShirtIcon from '@lucide/vue/dist/esm/icons/shirt.mjs'
import LucideShoppingBagIcon from '@lucide/vue/dist/esm/icons/shopping-bag.mjs'
import LucideShoppingBasketIcon from '@lucide/vue/dist/esm/icons/shopping-basket.mjs'
import LucideShoppingCartIcon from '@lucide/vue/dist/esm/icons/shopping-cart.mjs'
import LucideShovelIcon from '@lucide/vue/dist/esm/icons/shovel.mjs'
import LucideShowerHeadIcon from '@lucide/vue/dist/esm/icons/shower-head.mjs'
import LucideShrinkIcon from '@lucide/vue/dist/esm/icons/shrink.mjs'
import LucideSigmaIcon from '@lucide/vue/dist/esm/icons/sigma.mjs'
import LucideSignalIcon from '@lucide/vue/dist/esm/icons/signal.mjs'
import LucideSignalHighIcon from '@lucide/vue/dist/esm/icons/signal-high.mjs'
import LucideSignalLowIcon from '@lucide/vue/dist/esm/icons/signal-low.mjs'
import LucideSignpostIcon from '@lucide/vue/dist/esm/icons/signpost.mjs'
import LucideSignpostBigIcon from '@lucide/vue/dist/esm/icons/signpost-big.mjs'
import LucideSirenIcon from '@lucide/vue/dist/esm/icons/siren.mjs'
import LucideSkipBackIcon from '@lucide/vue/dist/esm/icons/skip-back.mjs'
import LucideSkipForwardIcon from '@lucide/vue/dist/esm/icons/skip-forward.mjs'
import LucideSlidersHorizontalIcon from '@lucide/vue/dist/esm/icons/sliders-horizontal.mjs'
import LucideSmartphoneIcon from '@lucide/vue/dist/esm/icons/smartphone.mjs'
import FaceSlightlySmilingIcon from '@lucide/vue/dist/esm/icons/face-slightly-smiling.mjs'
import LucideSnailIcon from '@lucide/vue/dist/esm/icons/snail.mjs'
import LucideSnowflakeIcon from '@lucide/vue/dist/esm/icons/snowflake.mjs'
import ArrowUpNarrowWideIcon from '@lucide/vue/dist/esm/icons/arrow-up-narrow-wide.mjs'
import ArrowDownWideNarrowIcon from '@lucide/vue/dist/esm/icons/arrow-down-wide-narrow.mjs'
import LucideSoupIcon from '@lucide/vue/dist/esm/icons/soup.mjs'
import LucideSpadeIcon from '@lucide/vue/dist/esm/icons/spade.mjs'
import LucideSparkleIcon from '@lucide/vue/dist/esm/icons/sparkle.mjs'
import LucideSparklesIcon from '@lucide/vue/dist/esm/icons/sparkles.mjs'
import LucideSpeakerIcon from '@lucide/vue/dist/esm/icons/speaker.mjs'
import LucideSpeechIcon from '@lucide/vue/dist/esm/icons/speech.mjs'
import LucideSpellCheckIcon from '@lucide/vue/dist/esm/icons/spell-check.mjs'
import LucideSplitIcon from '@lucide/vue/dist/esm/icons/split.mjs'
import LucideSproutIcon from '@lucide/vue/dist/esm/icons/sprout.mjs'
import LucideSquareIcon from '@lucide/vue/dist/esm/icons/square.mjs'
import ArrowDownLeftFromSquareIcon from '@lucide/vue/dist/esm/icons/square-arrow-out-down-left.mjs'
import ArrowDownRightFromSquareIcon from '@lucide/vue/dist/esm/icons/square-arrow-out-down-right.mjs'
import ArrowUpLeftFromSquareIcon from '@lucide/vue/dist/esm/icons/square-arrow-out-up-left.mjs'
import ArrowUpRightFromSquareIcon from '@lucide/vue/dist/esm/icons/square-arrow-out-up-right.mjs'
import CheckSquare2Icon from '@lucide/vue/dist/esm/icons/square-check.mjs'
import KanbanSquareIcon from '@lucide/vue/dist/esm/icons/square-kanban.mjs'
import LucideMinusSquareIcon from '@lucide/vue/dist/esm/icons/square-minus.mjs'
import LucidePlusSquareIcon from '@lucide/vue/dist/esm/icons/square-plus.mjs'
import LucideSquareXIcon from '@lucide/vue/dist/esm/icons/square-x.mjs'
import LucideSquirrelIcon from '@lucide/vue/dist/esm/icons/squirrel.mjs'
import LucideStampIcon from '@lucide/vue/dist/esm/icons/stamp.mjs'
import LucideStarIcon from '@lucide/vue/dist/esm/icons/star.mjs'
import LucideStethoscopeIcon from '@lucide/vue/dist/esm/icons/stethoscope.mjs'
import LucideStickyNoteIcon from '@lucide/vue/dist/esm/icons/sticky-note.mjs'
import LucideStoreIcon from '@lucide/vue/dist/esm/icons/store.mjs'
import LucideSunIcon from '@lucide/vue/dist/esm/icons/sun.mjs'
import LucideSunriseIcon from '@lucide/vue/dist/esm/icons/sunrise.mjs'
import LucideSunsetIcon from '@lucide/vue/dist/esm/icons/sunset.mjs'
import LucideSwordsIcon from '@lucide/vue/dist/esm/icons/swords.mjs'
import LucideSyringeIcon from '@lucide/vue/dist/esm/icons/syringe.mjs'
import LucideTableIcon from '@lucide/vue/dist/esm/icons/table.mjs'
import LucideTable2Icon from '@lucide/vue/dist/esm/icons/table-2.mjs'
import LucideTablePropertiesIcon from '@lucide/vue/dist/esm/icons/table-properties.mjs'
import LucideTabletIcon from '@lucide/vue/dist/esm/icons/tablet.mjs'
import LucideTabletSmartphoneIcon from '@lucide/vue/dist/esm/icons/tablet-smartphone.mjs'
import LucideTagIcon from '@lucide/vue/dist/esm/icons/tag.mjs'
import LucideTagsIcon from '@lucide/vue/dist/esm/icons/tags.mjs'
import LucideTargetIcon from '@lucide/vue/dist/esm/icons/target.mjs'
import LucideTelescopeIcon from '@lucide/vue/dist/esm/icons/telescope.mjs'
import LucideTentIcon from '@lucide/vue/dist/esm/icons/tent.mjs'
import LucideTerminalIcon from '@lucide/vue/dist/esm/icons/terminal.mjs'
import LucideTestTubeIcon from '@lucide/vue/dist/esm/icons/test-tube.mjs'
import LucideTextCursorIcon from '@lucide/vue/dist/esm/icons/text-cursor.mjs'
import LucideTextSearchIcon from '@lucide/vue/dist/esm/icons/text-search.mjs'
import LucideThermometerIcon from '@lucide/vue/dist/esm/icons/thermometer.mjs'
import LucideThermometerSnowflakeIcon from '@lucide/vue/dist/esm/icons/thermometer-snowflake.mjs'
import LucideThermometerSunIcon from '@lucide/vue/dist/esm/icons/thermometer-sun.mjs'
import LucideThumbsDownIcon from '@lucide/vue/dist/esm/icons/thumbs-down.mjs'
import LucideThumbsUpIcon from '@lucide/vue/dist/esm/icons/thumbs-up.mjs'
import LucideTicketIcon from '@lucide/vue/dist/esm/icons/ticket.mjs'
import LucideTicketCheckIcon from '@lucide/vue/dist/esm/icons/ticket-check.mjs'
import LucideTicketMinusIcon from '@lucide/vue/dist/esm/icons/ticket-minus.mjs'
import LucideTicketPercentIcon from '@lucide/vue/dist/esm/icons/ticket-percent.mjs'
import LucideTicketPlusIcon from '@lucide/vue/dist/esm/icons/ticket-plus.mjs'
import LucideTicketXIcon from '@lucide/vue/dist/esm/icons/ticket-x.mjs'
import LucideTimerIcon from '@lucide/vue/dist/esm/icons/timer.mjs'
import LucideTimerOffIcon from '@lucide/vue/dist/esm/icons/timer-off.mjs'
import LucideTimerResetIcon from '@lucide/vue/dist/esm/icons/timer-reset.mjs'
import LucideToggleLeftIcon from '@lucide/vue/dist/esm/icons/toggle-left.mjs'
import LucideToggleRightIcon from '@lucide/vue/dist/esm/icons/toggle-right.mjs'
import LucideTouchpadIcon from '@lucide/vue/dist/esm/icons/touchpad.mjs'
import LucideTrafficConeIcon from '@lucide/vue/dist/esm/icons/traffic-cone.mjs'
import LucideTrainIcon from '@lucide/vue/dist/esm/icons/tram-front.mjs'
import LucideTrainFrontIcon from '@lucide/vue/dist/esm/icons/train-front.mjs'
import LucideTrashIcon from '@lucide/vue/dist/esm/icons/trash.mjs'
import LucideTreePineIcon from '@lucide/vue/dist/esm/icons/tree-pine.mjs'
import LucideTreesIcon from '@lucide/vue/dist/esm/icons/trees.mjs'
import LucideTriangleIcon from '@lucide/vue/dist/esm/icons/triangle.mjs'
import LucideTrophyIcon from '@lucide/vue/dist/esm/icons/trophy.mjs'
import LucideTruckIcon from '@lucide/vue/dist/esm/icons/truck.mjs'
import LucideTurtleIcon from '@lucide/vue/dist/esm/icons/turtle.mjs'
import LucideTvIcon from '@lucide/vue/dist/esm/icons/tv.mjs'
import LucideTypeIcon from '@lucide/vue/dist/esm/icons/type.mjs'
import LucideUmbrellaIcon from '@lucide/vue/dist/esm/icons/umbrella.mjs'
import LucideUnderlineIcon from '@lucide/vue/dist/esm/icons/underline.mjs'
import LucideUndoIcon from '@lucide/vue/dist/esm/icons/undo.mjs'
import LucideSchool2Icon from '@lucide/vue/dist/esm/icons/university.mjs'
import LucideUnlinkIcon from '@lucide/vue/dist/esm/icons/unlink.mjs'
import LucideUnlink2Icon from '@lucide/vue/dist/esm/icons/unlink-2.mjs'
import LucideUploadIcon from '@lucide/vue/dist/esm/icons/upload.mjs'
import LucideUsbIcon from '@lucide/vue/dist/esm/icons/usb.mjs'
import LucideUserIcon from '@lucide/vue/dist/esm/icons/user.mjs'
import LucideUserCheckIcon from '@lucide/vue/dist/esm/icons/user-check.mjs'
import LucideUserCogIcon from '@lucide/vue/dist/esm/icons/user-cog.mjs'
import LucideUserMinusIcon from '@lucide/vue/dist/esm/icons/user-minus.mjs'
import LucideUserPlusIcon from '@lucide/vue/dist/esm/icons/user-plus.mjs'
import LucideUser2Icon from '@lucide/vue/dist/esm/icons/user-round.mjs'
import LucideUserCheck2Icon from '@lucide/vue/dist/esm/icons/user-round-check.mjs'
import LucideUserCog2Icon from '@lucide/vue/dist/esm/icons/user-round-cog.mjs'
import LucideUserMinus2Icon from '@lucide/vue/dist/esm/icons/user-round-minus.mjs'
import LucideUserPlus2Icon from '@lucide/vue/dist/esm/icons/user-round-plus.mjs'
import LucideUserRoundSearchIcon from '@lucide/vue/dist/esm/icons/user-round-search.mjs'
import LucideUserRoundXIcon from '@lucide/vue/dist/esm/icons/user-round-x.mjs'
import LucideUserSearchIcon from '@lucide/vue/dist/esm/icons/user-search.mjs'
import LucideUserXIcon from '@lucide/vue/dist/esm/icons/user-x.mjs'
import LucideUsersIcon from '@lucide/vue/dist/esm/icons/users.mjs'
import LucideUsers2Icon from '@lucide/vue/dist/esm/icons/users-round.mjs'
import ForkKnifeIcon from '@lucide/vue/dist/esm/icons/utensils.mjs'
import ForkKnifeCrossedIcon from '@lucide/vue/dist/esm/icons/utensils-crossed.mjs'
import LucideVariableIcon from '@lucide/vue/dist/esm/icons/variable.mjs'
import LucideVideoIcon from '@lucide/vue/dist/esm/icons/video.mjs'
import LucideVideoOffIcon from '@lucide/vue/dist/esm/icons/video-off.mjs'
import LucideVoicemailIcon from '@lucide/vue/dist/esm/icons/voicemail.mjs'
import LucideVolume2Icon from '@lucide/vue/dist/esm/icons/volume-2.mjs'
import LucideVolumeXIcon from '@lucide/vue/dist/esm/icons/volume-x.mjs'
import LucideWalletIcon from '@lucide/vue/dist/esm/icons/wallet.mjs'
import LucideWand2Icon from '@lucide/vue/dist/esm/icons/wand-sparkles.mjs'
import LucideWarehouseIcon from '@lucide/vue/dist/esm/icons/warehouse.mjs'
import LucideWashingMachineIcon from '@lucide/vue/dist/esm/icons/washing-machine.mjs'
import LucideWatchIcon from '@lucide/vue/dist/esm/icons/watch.mjs'
import LucideWaypointsIcon from '@lucide/vue/dist/esm/icons/waypoints.mjs'
import LucideWebcamIcon from '@lucide/vue/dist/esm/icons/webcam.mjs'
import LucideWheatIcon from '@lucide/vue/dist/esm/icons/wheat.mjs'
import LucideWholeWordIcon from '@lucide/vue/dist/esm/icons/whole-word.mjs'
import LucideWifiIcon from '@lucide/vue/dist/esm/icons/wifi.mjs'
import LucideWindIcon from '@lucide/vue/dist/esm/icons/wind.mjs'
import LucideWorkflowIcon from '@lucide/vue/dist/esm/icons/workflow.mjs'
import LucideWormIcon from '@lucide/vue/dist/esm/icons/worm.mjs'
import LucideWrenchIcon from '@lucide/vue/dist/esm/icons/wrench.mjs'
import LucideXIcon from '@lucide/vue/dist/esm/icons/x.mjs'
import LucideZapIcon from '@lucide/vue/dist/esm/icons/zap.mjs'
import LucideZapOffIcon from '@lucide/vue/dist/esm/icons/zap-off.mjs'

export const iconRegistry: Record<IconographyName, Component> = {
  'accessibility': AccessibilityIcon,
  'activity': ActivityIcon,
  'air-vent': AirVentIcon,
  'airplay': AirplayIcon,
  'alarm-clock': AlarmClockIcon,
  'album': AlbumIcon,
  'alert-circle': AlertCircleIcon,
  'alert-triangle': AlertTriangleIcon,
  'align-center': AlignCenterIcon,
  'align-left': AlignLeftIcon,
  'align-right': AlignRightIcon,
  'ambulance': AmbulanceIcon,
  'anchor': AnchorIcon,
  'antenna': AntennaIcon,
  'aperture': ApertureIcon,
  'apple': AppleIcon,
  'archive': ArchiveIcon,
  'archive-restore': ArchiveRestoreIcon,
  'archive-x': ArchiveXIcon,
  'area-chart': AreaChartIcon,
  'armchair': ArmchairIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-up': ArrowUpIcon,
  'arrow-up-right': ArrowUpRightIcon,
  'asterisk': AsteriskIcon,
  'at-sign': AtSignIcon,
  'atom': AtomIcon,
  'award': AwardIcon,
  'axe': AxeIcon,
  'baby': BabyIcon,
  'badge': BadgeIcon,
  'badge-alert': BadgeAlertIcon,
  'badge-cent': BadgeCentIcon,
  'badge-check': BadgeCheckIcon,
  'badge-dollar-sign': BadgeDollarSignIcon,
  'badge-euro': BadgeEuroIcon,
  'badge-info': BadgeInfoIcon,
  'badge-minus': BadgeMinusIcon,
  'badge-plus': BadgePlusIcon,
  'badge-x': BadgeXIcon,
  'ban': BanIcon,
  'banana': BananaIcon,
  'banknote': BanknoteIcon,
  'bar-chart-2': BarChart2Icon,
  'bar-chart-3': BarChart3Icon,
  'barcode': BarcodeIcon,
  'bath': BathIcon,
  'battery': BatteryIcon,
  'battery-charging': BatteryChargingIcon,
  'battery-full': BatteryFullIcon,
  'battery-low': BatteryLowIcon,
  'beaker': BeakerIcon,
  'bed': BedIcon,
  'bed-double': BedDoubleIcon,
  'bed-single': BedSingleIcon,
  'beef': BeefIcon,
  'bell': BellIcon,
  'bell-minus': BellMinusIcon,
  'bell-off': BellOffIcon,
  'bell-plus': BellPlusIcon,
  'bell-ring': BellRingIcon,
  'bike': BikeIcon,
  'binary': BinaryIcon,
  'bird': BirdIcon,
  'blocks': BlocksIcon,
  'bluetooth': BluetoothIcon,
  'bold': BoldIcon,
  'bolt': BoltIcon,
  'bone': BoneIcon,
  'book': BookIcon,
  'book-check': BookCheckIcon,
  'book-copy': BookCopyIcon,
  'book-marked': BookMarkedIcon,
  'book-minus': BookMinusIcon,
  'book-open': BookOpenIcon,
  'book-open-check': BookOpenCheckIcon,
  'book-open-text': BookOpenTextIcon,
  'book-plus': BookPlusIcon,
  'book-text': BookTextIcon,
  'book-user': BookUserIcon,
  'book-x': BookXIcon,
  'bookmark': BookmarkIcon,
  'bookmark-minus': BookmarkMinusIcon,
  'bookmark-plus': BookmarkPlusIcon,
  'bookmark-x': BookmarkXIcon,
  'bot': BotIcon,
  'box': BoxIcon,
  'boxes': BoxesIcon,
  'brain': BrainIcon,
  'brain-circuit': BrainCircuitIcon,
  'brain-cog': BrainCogIcon,
  'brick-wall': BrickWallIcon,
  'briefcase': BriefcaseIcon,
  'brush': BrushIcon,
  'brush-cleaning': BrushCleaningIcon,
  'bug': BugIcon,
  'bug-off': BugOffIcon,
  'bug-play': BugPlayIcon,
  'building': BuildingIcon,
  'building-2': Building2Icon,
  'bus': BusIcon,
  'bus-front': BusFrontIcon,
  'cake': CakeIcon,
  'cake-slice': CakeSliceIcon,
  'calendar': CalendarIcon,
  'calendar-check': CalendarCheckIcon,
  'calendar-clock': CalendarClockIcon,
  'calendar-days': CalendarDaysIcon,
  'calendar-heart': CalendarHeartIcon,
  'calendar-minus': CalendarMinusIcon,
  'calendar-plus': CalendarPlusIcon,
  'calendar-range': CalendarRangeIcon,
  'calendar-search': CalendarSearchIcon,
  'calendar-x': CalendarXIcon,
  'camera': CameraIcon,
  'candy': CandyIcon,
  'candy-cane': CandyCaneIcon,
  'car': CarIcon,
  'car-front': CarFrontIcon,
  'car-taxi-front': CarTaxiFrontIcon,
  'carrot': CarrotIcon,
  'case-lower': CaseLowerIcon,
  'case-sensitive': CaseSensitiveIcon,
  'case-upper': CaseUpperIcon,
  'cast': CastIcon,
  'castle': CastleIcon,
  'cat': CatIcon,
  'check': CheckIcon,
  'check-circle': CheckCircleIcon,
  'chef-hat': ChefHatIcon,
  'cherry': CherryIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-up': ChevronUpIcon,
  'chevrons-left': ChevronsLeftIcon,
  'chevrons-right': ChevronsRightIcon,
  'church': ChurchIcon,
  'cigarette': CigaretteIcon,
  'cigarette-off': CigaretteOffIcon,
  'circle': CircleIcon,
  'circle-check': CheckCircle2Icon,
  'circle-dollar-sign': CircleDollarSignIcon,
  'circle-dot': CircleDotIcon,
  'circle-minus': CircleMinusIcon,
  'circle-off': CircleOffIcon,
  'circle-plus': CirclePlusIcon,
  'circle-x': CircleXIcon,
  'circuit-board': CircuitBoardIcon,
  'citrus': CitrusIcon,
  'clapperboard': ClapperboardIcon,
  'clipboard': ClipboardIcon,
  'clipboard-check': ClipboardCheckIcon,
  'clipboard-copy': ClipboardCopyIcon,
  'clipboard-list': ClipboardListIcon,
  'clipboard-paste': ClipboardPasteIcon,
  'clipboard-x': ClipboardXIcon,
  'clock': ClockIcon,
  'cloud': CloudIcon,
  'cloud-download': CloudDownloadIcon,
  'cloud-drizzle': CloudDrizzleIcon,
  'cloud-fog': CloudFogIcon,
  'cloud-hail': CloudHailIcon,
  'cloud-lightning': CloudLightningIcon,
  'cloud-moon': CloudMoonIcon,
  'cloud-off': CloudOffIcon,
  'cloud-rain': CloudRainIcon,
  'cloud-snow': CloudSnowIcon,
  'cloud-sun': CloudSunIcon,
  'cloud-upload': CloudUploadIcon,
  'club': ClubIcon,
  'code': CodeIcon,
  'coffee': CoffeeIcon,
  'cog': CogIcon,
  'columns': ColumnsIcon,
  'columns-2': ColumnsIcon,
  'columns-3': Columns3Icon,
  'columns-4': Columns4Icon,
  'combine': CombineIcon,
  'compass': CompassIcon,
  'component': ComponentIcon,
  'construction': ConstructionIcon,
  'contact': ContactIcon,
  'contact-2': Contact2Icon,
  'contact-round': Contact2Icon,
  'container': ContainerIcon,
  'contrast': ContrastIcon,
  'cookie': CookieIcon,
  'cooking-pot': CookingPotIcon,
  'copy': CopyIcon,
  'cpu': CpuIcon,
  'credit-card': CreditCardIcon,
  'crop': CropIcon,
  'cross': CrossIcon,
  'crosshair': CrosshairIcon,
  'crown': CrownIcon,
  'database': DatabaseIcon,
  'diamond': DiamondIcon,
  'disc': DiscIcon,
  'disc-2': Disc2Icon,
  'dna': DnaIcon,
  'dog': DogIcon,
  'dollar-sign': DollarSignIcon,
  'door-closed': DoorClosedIcon,
  'door-open': DoorOpenIcon,
  'download': DownloadIcon,
  'download-cloud': CloudDownloadIcon,
  'drafting-compass': DraftingCompassIcon,
  'droplet': DropletIcon,
  'droplets': DropletsIcon,
  'ear': EarIcon,
  'ear-off': EarOffIcon,
  'earth': EarthIcon,
  'eclipse': EclipseIcon,
  'edit': EditIcon,
  'egg': EggIcon,
  'egg-fried': EggFriedIcon,
  'eraser': EraserIcon,
  'ethernet-port': EthernetPortIcon,
  'euro': EuroIcon,
  'ev-charger': EvChargerIcon,
  'expand': ExpandIcon,
  'external-link': ExternalLinkIcon,
  'eye': EyeIcon,
  'eye-closed': EyeClosedIcon,
  'eye-off': EyeOffIcon,
  'factory': FactoryIcon,
  'fan': FanIcon,
  'fence': FenceIcon,
  'file': FileIcon,
  'file-audio': FileAudioIcon,
  'file-box': FileBoxIcon,
  'file-check': FileCheckIcon,
  'file-code': FileCodeIcon,
  'file-down': FileDownIcon,
  'file-image': FileImageIcon,
  'file-input': FileInputIcon,
  'file-json': FileBracesIcon,
  'file-minus': FileMinusIcon,
  'file-output': FileOutputIcon,
  'file-pen': FileEditIcon,
  'file-plus': FilePlusIcon,
  'file-question': FileQuestionIcon,
  'file-search': FileSearchIcon,
  'file-signature': FilePenLineIcon,
  'file-sliders': FileSlidersIcon,
  'file-spreadsheet': FileSpreadsheetIcon,
  'file-stack': FileStackIcon,
  'file-symlink': FileSymlinkIcon,
  'file-text': FileTextIcon,
  'file-type': FileTypeIcon,
  'file-type-2': FileType2Icon,
  'file-up': FileUpIcon,
  'file-user': FileUserIcon,
  'file-video': FilePlayIcon,
  'file-volume': FileVolumeIcon,
  'file-warning': FileExclamationPointIcon,
  'file-x': FileXIcon,
  'files': FilesIcon,
  'film': FilmIcon,
  'filter': FilterIcon,
  'fingerprint': FingerprintIcon,
  'fire-extinguisher': FireExtinguisherIcon,
  'fish': FishIcon,
  'fish-off': FishOffIcon,
  'flag': FlagIcon,
  'flag-off': FlagOffIcon,
  'flame': FlameIcon,
  'flashlight': FlashlightIcon,
  'flask-conical': FlaskConicalIcon,
  'flip-horizontal': FlipHorizontalIcon,
  'flip-vertical': FlipVerticalIcon,
  'flower': FlowerIcon,
  'focus': FocusIcon,
  'folder': FolderIcon,
  'folder-archive': FolderArchiveIcon,
  'folder-check': FolderCheckIcon,
  'folder-cog': FolderCogIcon,
  'folder-dot': FolderDotIcon,
  'folder-down': FolderDownIcon,
  'folder-git': FolderGitIcon,
  'folder-git-2': FolderGit2Icon,
  'folder-heart': FolderHeartIcon,
  'folder-input': FolderInputIcon,
  'folder-kanban': FolderKanbanIcon,
  'folder-key': FolderKeyIcon,
  'folder-lock': FolderLockIcon,
  'folder-minus': FolderMinusIcon,
  'folder-open': FolderOpenIcon,
  'folder-output': FolderOutputIcon,
  'folder-pen': FolderEditIcon,
  'folder-plus': FolderPlusIcon,
  'folder-search': FolderSearchIcon,
  'folder-sync': FolderSyncIcon,
  'folder-tree': FolderTreeIcon,
  'folder-up': FolderUpIcon,
  'folder-x': FolderXIcon,
  'footprints': FootprintsIcon,
  'forklift': ForkliftIcon,
  'forward': ForwardIcon,
  'frown': FaceSlightlyFrowningIcon,
  'fuel': FuelIcon,
  'fullscreen': FullscreenIcon,
  'gallery-horizontal': GalleryHorizontalIcon,
  'gallery-thumbnails': GalleryThumbnailsIcon,
  'gallery-vertical': GalleryVerticalIcon,
  'gamepad': GamepadIcon,
  'gamepad-2': Gamepad2Icon,
  'gavel': GavelIcon,
  'gem': GemIcon,
  'gift': GiftIcon,
  'git-branch': GitBranchIcon,
  'git-commit': GitCommitIcon,
  'git-fork': GitForkIcon,
  'git-merge': GitMergeIcon,
  'git-pull-request': GitPullRequestIcon,
  'glass-water': GlassWaterIcon,
  'glasses': GlassesIcon,
  'globe': GlobeIcon,
  'globe-2': EarthIcon,
  'globe-lock': GlobeLockIcon,
  'graduation-cap': GraduationCapIcon,
  'grape': GrapeIcon,
  'grid-3x3': GridIcon,
  'grip-vertical': GripVerticalIcon,
  'ham': HamIcon,
  'hammer': HammerIcon,
  'hand': HandIcon,
  'hand-coins': HandCoinsIcon,
  'hand-heart': HandHeartIcon,
  'hand-helping': HandHelpingIcon,
  'hand-metal': HandMetalIcon,
  'hand-platter': HandPlatterIcon,
  'handshake': HandshakeIcon,
  'hard-drive': HardDriveIcon,
  'hard-drive-download': HardDriveDownloadIcon,
  'hard-drive-upload': HardDriveUploadIcon,
  'hard-hat': HardHatIcon,
  'hash': HashIcon,
  'heading': HeadingIcon,
  'headphones': HeadphonesIcon,
  'heart': HeartIcon,
  'heart-handshake': HeartHandshakeIcon,
  'heart-pulse': HeartPulseIcon,
  'heater': HeaterIcon,
  'helicopter': HelicopterIcon,
  'help-circle': CircleHelpIcon,
  'hexagon': HexagonIcon,
  'highlighter': HighlighterIcon,
  'history': HistoryIcon,
  'home': HomeIcon,
  'hospital': HospitalIcon,
  'hotel': HotelIcon,
  'hourglass': HourglassIcon,
  'house': HomeIcon,
  'house-heart': HouseHeartIcon,
  'house-plug': HousePlugIcon,
  'house-plus': HousePlusIcon,
  'house-wifi': HouseWifiIcon,
  'ice-cream-bowl': IceCream2Icon,
  'ice-cream-cone': IceCreamIcon,
  'id-card': IdCardIcon,
  'image': ImageIcon,
  'image-down': ImageDownIcon,
  'image-minus': ImageMinusIcon,
  'image-off': ImageOffIcon,
  'image-play': ImagePlayIcon,
  'image-plus': ImagePlusIcon,
  'image-up': ImageUpIcon,
  'images': ImagesIcon,
  'inbox': InboxIcon,
  'infinity': InfinityIcon,
  'info': InfoIcon,
  'italic': ItalicIcon,
  'joystick': JoystickIcon,
  'kanban': KanbanIcon,
  'key': KeyIcon,
  'key-round': KeyRoundIcon,
  'key-square': KeySquareIcon,
  'keyboard': KeyboardIcon,
  'lamp': LampIcon,
  'landmark': LandmarkIcon,
  'languages': LanguagesIcon,
  'laptop': LaptopIcon,
  'laugh': FaceGrinningIcon,
  'layers': LayersIcon,
  'layout-dashboard': LayoutDashboardIcon,
  'layout-grid': LayoutGridIcon,
  'layout-list': LayoutListIcon,
  'layout-panel-left': LayoutPanelLeftIcon,
  'layout-panel-top': LayoutPanelTopIcon,
  'layout-template': LayoutTemplateIcon,
  'leaf': LeafIcon,
  'library': LibraryIcon,
  'library-big': LibraryBigIcon,
  'life-buoy': LifeBuoyIcon,
  'lightbulb': LightbulbIcon,
  'line-chart': ChartLineIcon,
  'link': LinkIcon,
  'link-2': Link2Icon,
  'list': ListIcon,
  'list-checks': ListChecksIcon,
  'list-collapse': ListCollapseIcon,
  'list-end': ListEndIcon,
  'list-filter': ListFilterIcon,
  'list-minus': ListMinusIcon,
  'list-ordered': ListOrderedIcon,
  'list-plus': ListPlusIcon,
  'list-restart': ListRestartIcon,
  'list-start': ListStartIcon,
  'list-todo': ListTodoIcon,
  'list-tree': ListTreeIcon,
  'list-x': ListXIcon,
  'loader-2': Loader2Icon,
  'locate': LocateIcon,
  'locate-fixed': LocateFixedIcon,
  'locate-off': LocateOffIcon,
  'lock': LockIcon,
  'lock-keyhole': LockKeyholeIcon,
  'lock-open': LockOpenIcon,
  'log-in': LogInIcon,
  'log-out': LogOutIcon,
  'lollipop': LollipopIcon,
  'magnet': LucideMagnetIcon,
  'mail': LucideMailIcon,
  'mail-check': LucideMailCheckIcon,
  'mail-minus': LucideMailMinusIcon,
  'mail-open': LucideMailOpenIcon,
  'mail-plus': LucideMailPlusIcon,
  'mail-question': LucideMailQuestionIcon,
  'mail-warning': LucideMailWarningIcon,
  'mail-x': LucideMailXIcon,
  'map': LucideMapIcon,
  'map-pin': LucideMapPinIcon,
  'map-pin-off': LucideMapPinOffIcon,
  'map-pinned': LucideMapPinnedIcon,
  'maximize': LucideMaximizeIcon,
  'maximize-2': LucideMaximize2Icon,
  'medal': LucideMedalIcon,
  'megaphone': LucideMegaphoneIcon,
  'meh': FaceNeutralIcon,
  'menu': LucideMenuIcon,
  'merge': LucideMergeIcon,
  'message-circle': LucideMessageCircleIcon,
  'message-square': LucideMessageSquareIcon,
  'messages-square': LucideMessagesSquareIcon,
  'mic': LucideMicIcon,
  'mic-2': LucideMic2Icon,
  'mic-off': LucideMicOffIcon,
  'microscope': LucideMicroscopeIcon,
  'microwave': LucideMicrowaveIcon,
  'milestone': LucideMilestoneIcon,
  'milk': LucideMilkIcon,
  'minimize': LucideMinimizeIcon,
  'minimize-2': LucideMinimize2Icon,
  'minus': LucideMinusIcon,
  'monitor': LucideMonitorIcon,
  'monitor-play': LucideMonitorPlayIcon,
  'monitor-smartphone': LucideMonitorSmartphoneIcon,
  'monitor-speaker': LucideMonitorSpeakerIcon,
  'moon': LucideMoonIcon,
  'moon-star': LucideMoonStarIcon,
  'more-horizontal': EllipsisIcon,
  'more-vertical': EllipsisVerticalIcon,
  'mountain': LucideMountainIcon,
  'mouse': LucideMouseIcon,
  'mouse-pointer': LucideMousePointerIcon,
  'mouse-pointer-2': LucideMousePointer2Icon,
  'move': LucideMoveIcon,
  'move-3d': LucideMove3DIcon,
  'music': LucideMusicIcon,
  'music-2': LucideMusic2Icon,
  'music-3': LucideMusic3Icon,
  'music-4': LucideMusic4Icon,
  'navigation': LucideNavigationIcon,
  'navigation-off': LucideNavigationOffIcon,
  'network': LucideNetworkIcon,
  'newspaper': LucideNewspaperIcon,
  'nfc': LucideNfcIcon,
  'notebook': LucideNotebookIcon,
  'notebook-pen': LucideNotebookPenIcon,
  'notebook-tabs': LucideNotebookTabsIcon,
  'notebook-text': LucideNotebookTextIcon,
  'notepad-text': LucideNotepadTextIcon,
  'nut': LucideNutIcon,
  'octagon': LucideOctagonIcon,
  'octagon-alert': AlertOctagonIcon,
  'orbit': LucideOrbitIcon,
  'package': LucidePackageIcon,
  'package-2': LucidePackage2Icon,
  'package-check': LucidePackageCheckIcon,
  'package-minus': LucidePackageMinusIcon,
  'package-open': LucidePackageOpenIcon,
  'package-plus': LucidePackagePlusIcon,
  'package-search': LucidePackageSearchIcon,
  'package-x': LucidePackageXIcon,
  'paintbrush': LucidePaintbrushIcon,
  'palette': LucidePaletteIcon,
  'panel-bottom': LucidePanelBottomIcon,
  'panel-left': LucidePanelLeftIcon,
  'panel-left-close': LucidePanelLeftCloseIcon,
  'panel-left-open': LucidePanelLeftOpenIcon,
  'panel-right': LucidePanelRightIcon,
  'panel-top': LucidePanelTopIcon,
  'paperclip': LucidePaperclipIcon,
  'parking-meter': LucideParkingMeterIcon,
  'pause': LucidePauseIcon,
  'paw-print': LucidePawPrintIcon,
  'pen-line': Edit3Icon,
  'pen-tool': LucidePenToolIcon,
  'pencil': LucidePencilIcon,
  'pencil-line': LucidePencilLineIcon,
  'pencil-ruler': LucidePencilRulerIcon,
  'pentagon': LucidePentagonIcon,
  'percent': LucidePercentIcon,
  'phone': LucidePhoneIcon,
  'phone-call': LucidePhoneCallIcon,
  'phone-forwarded': LucidePhoneForwardedIcon,
  'phone-incoming': LucidePhoneIncomingIcon,
  'phone-missed': LucidePhoneMissedIcon,
  'phone-off': LucidePhoneOffIcon,
  'phone-outgoing': LucidePhoneOutgoingIcon,
  'pi': LucidePiIcon,
  'pickaxe': LucidePickaxeIcon,
  'picture-in-picture': LucidePictureInPictureIcon,
  'picture-in-picture-2': LucidePictureInPicture2Icon,
  'pie-chart': ChartPieIcon,
  'piggy-bank': LucidePiggyBankIcon,
  'pilcrow': LucidePilcrowIcon,
  'pill': LucidePillIcon,
  'pill-bottle': LucidePillBottleIcon,
  'pin': LucidePinIcon,
  'pin-off': LucidePinOffIcon,
  'pizza': LucidePizzaIcon,
  'plane': LucidePlaneIcon,
  'plane-landing': LucidePlaneLandingIcon,
  'plane-takeoff': LucidePlaneTakeoffIcon,
  'play': LucidePlayIcon,
  'plug': LucidePlugIcon,
  'plug-zap': LucidePlugZapIcon,
  'plus': LucidePlusIcon,
  'popcorn': LucidePopcornIcon,
  'power': LucidePowerIcon,
  'presentation': LucidePresentationIcon,
  'printer': LucidePrinterIcon,
  'projector': LucideProjectorIcon,
  'puzzle': LucidePuzzleIcon,
  'qr-code': LucideQrCodeIcon,
  'quote': LucideQuoteIcon,
  'rabbit': LucideRabbitIcon,
  'radar': LucideRadarIcon,
  'radio': LucideRadioIcon,
  'radio-tower': LucideRadioTowerIcon,
  'rat': LucideRatIcon,
  'ratio': LucideRatioIcon,
  'receipt': LucideReceiptIcon,
  'receipt-cent': LucideReceiptCentIcon,
  'receipt-text': LucideReceiptTextIcon,
  'recycle': LucideRecycleIcon,
  'redo': LucideRedoIcon,
  'refresh-ccw': LucideRefreshCcwIcon,
  'refresh-cw': LucideRefreshCwIcon,
  'refresh-cw-off': LucideRefreshCwOffIcon,
  'refrigerator': LucideRefrigeratorIcon,
  'remove-formatting': LucideRemoveFormattingIcon,
  'reply': LucideReplyIcon,
  'reply-all': LucideReplyAllIcon,
  'rocket': LucideRocketIcon,
  'rocking-chair': LucideRockingChairIcon,
  'rotate-3d': LucideRotate3DIcon,
  'rotate-ccw': LucideRotateCcwIcon,
  'route': LucideRouteIcon,
  'route-off': LucideRouteOffIcon,
  'router': LucideRouterIcon,
  'rows': LucideRowsIcon,
  'rows-2': LucideRowsIcon,
  'rows-3': LucidePanelsTopBottomIcon,
  'rows-4': LucideRows4Icon,
  'rss': LucideRssIcon,
  'ruler': LucideRulerIcon,
  'sailboat': LucideSailboatIcon,
  'salad': LucideSaladIcon,
  'sandwich': LucideSandwichIcon,
  'satellite': LucideSatelliteIcon,
  'satellite-dish': LucideSatelliteDishIcon,
  'save': LucideSaveIcon,
  'scale': LucideScaleIcon,
  'scan': LucideScanIcon,
  'scan-barcode': LucideScanBarcodeIcon,
  'scan-eye': LucideScanEyeIcon,
  'scan-face': LucideScanFaceIcon,
  'scan-heart': LucideScanHeartIcon,
  'scan-line': LucideScanLineIcon,
  'scan-search': LucideScanSearchIcon,
  'scan-text': LucideScanTextIcon,
  'school': LucideSchoolIcon,
  'scissors': LucideScissorsIcon,
  'screen-share': LucideScreenShareIcon,
  'screen-share-off': LucideScreenShareOffIcon,
  'scroll': LucideScrollIcon,
  'scroll-text': LucideScrollTextIcon,
  'search': LucideSearchIcon,
  'send': LucideSendIcon,
  'send-horizontal': LucideSendHorizonalIcon,
  'server': LucideServerIcon,
  'server-cog': LucideServerCogIcon,
  'server-crash': LucideServerCrashIcon,
  'server-off': LucideServerOffIcon,
  'settings': LucideSettingsIcon,
  'shapes': LucideShapesIcon,
  'share': LucideShareIcon,
  'share-2': LucideShare2Icon,
  'sheet': LucideSheetIcon,
  'shell': LucideShellIcon,
  'shield': LucideShieldIcon,
  'shield-alert': LucideShieldAlertIcon,
  'shield-ban': LucideShieldBanIcon,
  'shield-check': LucideShieldCheckIcon,
  'shield-half': LucideShieldHalfIcon,
  'shield-question': LucideShieldQuestionIcon,
  'shield-x': LucideShieldCloseIcon,
  'ship': LucideShipIcon,
  'ship-wheel': LucideShipWheelIcon,
  'shirt': LucideShirtIcon,
  'shopping-bag': LucideShoppingBagIcon,
  'shopping-basket': LucideShoppingBasketIcon,
  'shopping-cart': LucideShoppingCartIcon,
  'shovel': LucideShovelIcon,
  'shower-head': LucideShowerHeadIcon,
  'shrink': LucideShrinkIcon,
  'sidebar': LucidePanelLeftIcon,
  'sigma': LucideSigmaIcon,
  'signal': LucideSignalIcon,
  'signal-high': LucideSignalHighIcon,
  'signal-low': LucideSignalLowIcon,
  'signpost': LucideSignpostIcon,
  'signpost-big': LucideSignpostBigIcon,
  'siren': LucideSirenIcon,
  'skip-back': LucideSkipBackIcon,
  'skip-forward': LucideSkipForwardIcon,
  'sliders-horizontal': LucideSlidersHorizontalIcon,
  'smartphone': LucideSmartphoneIcon,
  'smile': FaceSlightlySmilingIcon,
  'snail': LucideSnailIcon,
  'snowflake': LucideSnowflakeIcon,
  'sort-asc': ArrowUpNarrowWideIcon,
  'sort-desc': ArrowDownWideNarrowIcon,
  'soup': LucideSoupIcon,
  'spade': LucideSpadeIcon,
  'sparkle': LucideSparkleIcon,
  'sparkles': LucideSparklesIcon,
  'speaker': LucideSpeakerIcon,
  'speech': LucideSpeechIcon,
  'spell-check': LucideSpellCheckIcon,
  'split': LucideSplitIcon,
  'sprout': LucideSproutIcon,
  'square': LucideSquareIcon,
  'square-arrow-out-down-left': ArrowDownLeftFromSquareIcon,
  'square-arrow-out-down-right': ArrowDownRightFromSquareIcon,
  'square-arrow-out-up-left': ArrowUpLeftFromSquareIcon,
  'square-arrow-out-up-right': ArrowUpRightFromSquareIcon,
  'square-check': CheckSquare2Icon,
  'square-kanban': KanbanSquareIcon,
  'square-minus': LucideMinusSquareIcon,
  'square-pen': EditIcon,
  'square-plus': LucidePlusSquareIcon,
  'square-x': LucideSquareXIcon,
  'squirrel': LucideSquirrelIcon,
  'stamp': LucideStampIcon,
  'star': LucideStarIcon,
  'stars': LucideSparklesIcon,
  'stethoscope': LucideStethoscopeIcon,
  'sticky-note': LucideStickyNoteIcon,
  'store': LucideStoreIcon,
  'sun': LucideSunIcon,
  'sunrise': LucideSunriseIcon,
  'sunset': LucideSunsetIcon,
  'swords': LucideSwordsIcon,
  'syringe': LucideSyringeIcon,
  'table': LucideTableIcon,
  'table-2': LucideTable2Icon,
  'table-properties': LucideTablePropertiesIcon,
  'tablet': LucideTabletIcon,
  'tablet-smartphone': LucideTabletSmartphoneIcon,
  'tag': LucideTagIcon,
  'tags': LucideTagsIcon,
  'target': LucideTargetIcon,
  'telescope': LucideTelescopeIcon,
  'tent': LucideTentIcon,
  'terminal': LucideTerminalIcon,
  'test-tube': LucideTestTubeIcon,
  'text': AlignLeftIcon,
  'text-cursor': LucideTextCursorIcon,
  'text-search': LucideTextSearchIcon,
  'thermometer': LucideThermometerIcon,
  'thermometer-snowflake': LucideThermometerSnowflakeIcon,
  'thermometer-sun': LucideThermometerSunIcon,
  'thumbs-down': LucideThumbsDownIcon,
  'thumbs-up': LucideThumbsUpIcon,
  'ticket': LucideTicketIcon,
  'ticket-check': LucideTicketCheckIcon,
  'ticket-minus': LucideTicketMinusIcon,
  'ticket-percent': LucideTicketPercentIcon,
  'ticket-plus': LucideTicketPlusIcon,
  'ticket-x': LucideTicketXIcon,
  'timer': LucideTimerIcon,
  'timer-off': LucideTimerOffIcon,
  'timer-reset': LucideTimerResetIcon,
  'toggle-left': LucideToggleLeftIcon,
  'toggle-right': LucideToggleRightIcon,
  'touchpad': LucideTouchpadIcon,
  'traffic-cone': LucideTrafficConeIcon,
  'train': LucideTrainIcon,
  'train-front': LucideTrainFrontIcon,
  'tram-front': LucideTrainIcon,
  'trash': LucideTrashIcon,
  'tree-pine': LucideTreePineIcon,
  'trees': LucideTreesIcon,
  'triangle': LucideTriangleIcon,
  'triangle-alert': AlertTriangleIcon,
  'trophy': LucideTrophyIcon,
  'truck': LucideTruckIcon,
  'turtle': LucideTurtleIcon,
  'tv': LucideTvIcon,
  'type': LucideTypeIcon,
  'umbrella': LucideUmbrellaIcon,
  'underline': LucideUnderlineIcon,
  'undo': LucideUndoIcon,
  'university': LucideSchool2Icon,
  'unlink': LucideUnlinkIcon,
  'unlink-2': LucideUnlink2Icon,
  'unlock': LockOpenIcon,
  'upload': LucideUploadIcon,
  'upload-cloud': CloudUploadIcon,
  'usb': LucideUsbIcon,
  'user': LucideUserIcon,
  'user-check': LucideUserCheckIcon,
  'user-cog': LucideUserCogIcon,
  'user-minus': LucideUserMinusIcon,
  'user-plus': LucideUserPlusIcon,
  'user-round': LucideUser2Icon,
  'user-round-check': LucideUserCheck2Icon,
  'user-round-cog': LucideUserCog2Icon,
  'user-round-minus': LucideUserMinus2Icon,
  'user-round-plus': LucideUserPlus2Icon,
  'user-round-search': LucideUserRoundSearchIcon,
  'user-round-x': LucideUserRoundXIcon,
  'user-search': LucideUserSearchIcon,
  'user-x': LucideUserXIcon,
  'users': LucideUsersIcon,
  'users-2': LucideUsers2Icon,
  'users-round': LucideUsers2Icon,
  'utensils': ForkKnifeIcon,
  'utensils-crossed': ForkKnifeCrossedIcon,
  'variable': LucideVariableIcon,
  'verified': BadgeCheckIcon,
  'video': LucideVideoIcon,
  'video-off': LucideVideoOffIcon,
  'voicemail': LucideVoicemailIcon,
  'volume-2': LucideVolume2Icon,
  'volume-x': LucideVolumeXIcon,
  'wallet': LucideWalletIcon,
  'wand-2': LucideWand2Icon,
  'warehouse': LucideWarehouseIcon,
  'washing-machine': LucideWashingMachineIcon,
  'watch': LucideWatchIcon,
  'waypoints': LucideWaypointsIcon,
  'webcam': LucideWebcamIcon,
  'wheat': LucideWheatIcon,
  'whole-word': LucideWholeWordIcon,
  'wifi': LucideWifiIcon,
  'wind': LucideWindIcon,
  'workflow': LucideWorkflowIcon,
  'worm': LucideWormIcon,
  'wrench': LucideWrenchIcon,
  'x': LucideXIcon,
  'x-circle': CircleXIcon,
  'zap': LucideZapIcon,
  'zap-off': LucideZapOffIcon,
}
