/** Generated by scripts/generate-icon-loaders.mjs — do not edit manually. */
import type { Component } from 'vue'
import type { IconographyName } from './iconography.meta'

export declare const iconRegistry: Record<IconographyName, Component>
