/** Generated by scripts/generate-icon-loaders.mjs — do not edit manually. */
import type { Component } from 'vue'

type LucideIconModule = { default: Component }

export default (): Promise<LucideIconModule> =>
  import('@lucide/vue/dist/esm/icons/map-pin.mjs')
